# Generated by Django 5.0.6 on 2024-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hope_country_workspace",
            "0002_alter_household_options_remove_household_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="name",
            field=models.CharField(default=1, max_length=255, verbose_name="Name"),
            preserve_default=False,
        ),
    ]
