repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.3.2"
    hooks:
    -   id: djade
        args: [--target-version, "5.1"]  # Use current Django version

  - repo: https://github.com/twisted/towncrier
    rev: 24.8.0
    hooks:
      - id: towncrier-check
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/saxix/pch
    rev: '0.1'
    hooks:
      - id: check-missed-migrations
        args:
          - src
        stages: [ pre-commit ]
        additional_dependencies: [ setuptools ]

      - id: check-untracked
        args:
          - src
          - tests
        stages: [ pre-push ]
