[build-system]
build-backend = "hatchling.build"
requires = [
  "hatch-vcs>=0.4",
  "hatchling>=1.25",
]

[project]
name = "hope-country-workspace"
version = "0.4.8"
description = "HOPE Country Workspace (HCW)"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "sax", email = "s.apostolico@gmail.com" },
]
requires-python = "==3.14.*"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "bitcaster-sdk>=0.1",
  "celery>=5.4",
  "deepdiff>=8.0.1",
  "deprecation>=2.1",
  "dictdiffer>=0.9",
  "django<6",
  "django-adminactions>=2.3",
  "django-adminfilters>=2.5.2",
  "django-anymail[mailjet]>=13",
  "django-cacheops>=7.1",
  "django-celery-beat>=2.6",
  "django-celery-boost>=0.8",
  "django-celery-results>=2.5.1",
  "django-concurrency>=2.6",
  "django-constance>=4.1.3",
  "django-csp",
  "django-debug-toolbar>=4.4.2",
  "django-environ>=0.11.2",
  "django-flags>=5.0.13",
  "django-jsoneditor>=0.2.4",
  "django-mptt>=0.16",
  "django-pghistory>=3.5.4",
  "django-regex>=0.5",
  "django-select2",
  "django-smart-admin>=2.6",
  "django-smart-env>=0.1",
  "django-storages[azure]>=1.14.4",
  "django-stubs-ext",
  "django-sysinfo>=2.6.2",
  "django-tailwind>=3.8",
  "djangorestframework>=3.15.1",
  "dukpy>=0.5",
  "flower>=2.0.1",
  "hope-flex-fields>=0.8.1",
  "hope-smart-export>=0.3",
  "hope-smart-import>=0.5",
  "notebook>=7.4.3",
  "numpy>=2.3",
  "openpyxl>=3.1.5",
  "pandas>=2.3",
  "phonenumbers>=9.0.8",
  "pillow>=11.2.1",
  "pre-commit>=4.2",
  "psycopg2-binary>=2.9.9",
  "python-redis-lock[django]>=4",
  "redis",
  "scikit-learn>=1.7",
  "sentry-sdk>=2.7.1",
  "social-auth-app-django",
  "torch>=2.7.1",
  "unicef-security>=1.5.1",
]
urls.Documentation = "https://unicef.github.io/hope-country-workspace/"
urls.Homepage = "https://github.com/unicef/hope-country-workspace"
urls.Issues = "https://github.com/unicef/hope-country-workspace/issues"
urls.Repository = "https://github.com/unicef/hope-country-workspace"
scripts.celery-monitor = "country_workspace.__monitor__:run"

[dependency-groups]
dev = [
  "bump2version",
  "djade",
  "django-browser-reload",
  "django-webtest",
  "factory-boy",
  "freezegun",
  "glom",
  "ipython",
  "mypy",
  "pdbpp",
  "pip",
  "pre-commit",
  "pyquery",
  "pytest",
  "pytest-celery",
  "pytest-coverage",
  "pytest-django",
  "pytest-echo",
  "pytest-factoryboy",
  "pytest-mock",
  "pytest-recording",
  "pytest-xdist",
  "responses",
  "ruff",
  "seleniumbase>4",
  "tox",
  "vcrpy",
]
docs = [
  "mkdocs",
  "mkdocs-awesome-pages-plugin",
  "mkdocs-gen-files",
  "mkdocs-material",
  "mkdocstrings-python",
]
type-check = [
  "types-python-dateutil",
  "types-requests",
]

[tool.hatch]
build.targets.sdist.include = [
  "src/country_workspace/**/*.*",
]
build.targets.wheel.packages = [
  "src/country_workspace",
]

[tool.uv]
package = true

[tool.django-stubs]
django_settings_module = "country_workspace.config.settings"
