[tox]
requires =
    tox>=4.2
    tox-gh-actions
    tox-uv>=1.20.2
env_list =
    lint
    mypy
    tests
    pkg_meta
skip_missing_interpreters = true

[testenv]
base_python = python3.13
skip_install = true
deps =
    pip
    uv
pass_env =
    DATABASE_HOPE_URL
    DATABASE_URL
    PYTHONDONTWRITEBYTECODE
    PYTHONPATH
    USER
set_env =
    PYTHONDONTWRITEBYTECODE = true
    PYTHONPATH = {toxinidir}/src
commands =
    {posargs:pytest tests -rw --headless}

[testenv:mypy]
description = run type check on code base
deps =
    django==5.2.*
commands =
    mypy --config-file mypy.ini {posargs:}
dependency_groups =
    dev
    type-check

[testenv:pkg_meta]
skip_install = true
deps =
    build
    twine
set_env =
    TWINE_PASSWORD = {env:TWINE_TEST_PASSWORD}
    TWINE_USERNAME = {env:TWINE_TEST_USERNAME:__token__}
commands =
    uv build --sdist -q --out-dir {env_tmp_dir} .
    uvx twine check {env_tmp_dir}{/}*
    uvx check-wheel-contents --ignore W002,W004,W009,W004 {env_tmp_dir}
    uv pip install --no-binary hope_country_workspace --find-links {env_tmp_dir} hope_country_workspace

[testenv:report]
commands =
    pip install coverage
    coverage html
