from ..settings import env  # type: ignore[attr-defined]

CELERY_ACCEPT_CONTENT = ["pickle", "json", "application/text", "application/json"]
CELERY_BROKER_URL = env("CELERY_BROKER_URL")
# This option controls how much time a task is considered active. If the task
# takes more time than this option specifies, Celery restarts the task on
# another worker.
CELERY_BROKER_VISIBILITY_VAR = env("CELERY_VISIBILITY_TIMEOUT")
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": CELERY_BROKER_VISIBILITY_VAR}

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"
CELERY_CREATE_MISSING_QUEUES = True

CELERY_TASK_ACKS_LATE = True
CELERY_TASK_ALWAYS_EAGER = env("CELERY_TASK_ALWAYS_EAGER")
CELERY_TASK_STORE_EAGER_RESULT = env("CELERY_TASK_STORE_EAGER_RESULT")
CELERY_TASK_DEFAULT_QUEUE = "queue_hcw"
CELERY_TASK_EAGER_PROPAGATES = env("CELERY_TASK_EAGER_PROPAGATES")
CELERY_TASK_IGNORE_RESULT = False
CELERY_TASK_PUBLISH_RETRY = True
CELERY_TASK_REVOKED_QUEUE = "queue_hcw_revoked"
CELERY_TASK_RESULT_EXPIRES = 86400 * 7  # keep results for 7 days
CELERY_TASK_SERIALIZER = "json"
CELERY_TASK_TIME_LIMIT = None
CELERY_TASK_TRACK_STARTED = True

CELERY_QUEUES = [CELERY_TASK_DEFAULT_QUEUE, CELERY_TASK_REVOKED_QUEUE]

CELERY_WORKER_DISABLE_RATE_LIMITS = False
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

CELERY_SEND_TASK_ERROR_EMAILS = False

CELERY_CACHE_BACKEND = "django-cache"

CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_PERSISTENT = True
CELERY_RESULT_EXPIRES = None
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_SERIALIZER = "json"

CELERY_BROKER_CONNECTION_RETRY = False
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = False

CELERY_TRACK_STARTED = True
