# Generated by Django 5.1.1 on 2024-10-09 06:19
from django.db import migrations
from typing import TYPE_CHECKING
from country_workspace.constants import HOUSEHOLD_CHECKER_NAME, INDIVIDUAL_CHECKER_NAME
from country_workspace.versions.utils import create_hope_field_definitions, create_hope_core_fieldset

if TYPE_CHECKING:
    from hope_flex_fields.models import FieldDefinition, Fieldset, DataChecker


def removes_hope_field_definitions(apps, schema_editor):
    fd: "FieldDefinition" = apps.get_model("hope_flex_fields", "FieldDefinition")
    fd.objects.filter(name__startswith="HOPE ").delete()


def removes_hope_core_fieldset(apps, schema_editor):
    fs: "Fieldset" = apps.get_model("hope_flex_fields", "Fieldset")
    dc: "DataChecker" = apps.get_model("hope_flex_fields", "DataChecker")

    fs.objects.filter(name=INDIVIDUAL_CHECKER_NAME).delete()
    dc.objects.filter(name=INDIVIDUAL_CHECKER_NAME).delete()
    dc.objects.filter(name=HOUSEHOLD_CHECKER_NAME).delete()
    fs.objects.filter(name=HOUSEHOLD_CHECKER_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [("hope_flex_fields", "0007_create_default_fields"),
                    ]

    operations = [
        migrations.RunPython(create_hope_field_definitions, removes_hope_field_definitions),
        migrations.RunPython(create_hope_core_fieldset, removes_hope_core_fieldset)

    ]
