# Generated by Django 5.0.6 on 2024-07-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryoffice",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
