# Generated by Django 5.0.6 on 2024-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_countryoffice_slug_userrole_expires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryoffice",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
