# Generated by Django 5.0.6 on 2024-07-03 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_countryoffice_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="expires",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
