# Generated by Django 5.0.6 on 2024-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_countryoffice_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryoffice",
            name="hope_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
