# Generated by Django 5.1.3 on 2025-02-05 11:24

import concurrency.fields
import django.db.models.deletion
import strategy_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0001_initial"),
        ("hope_flex_fields", "0013_fielddefinition_validated_alter_datachecker_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="active",
            field=models.BooleanField(
                default=False, help_text="Whether the program is active. Only active program are visible in the UI"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="beneficiary_validator",
            field=strategy_field.fields.StrategyField(
                blank=True,
                default="country_workspace.validators.registry.NoopValidator",
                help_text="Validator to use to validate the whole Household",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="household_checker",
            field=models.ForeignKey(
                blank=True,
                help_text="Checker to use with Household's records",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="hope_flex_fields.datachecker",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="individual_checker",
            field=models.ForeignKey(
                blank=True,
                help_text="Checker to use with Individual's records",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="hope_flex_fields.datachecker",
            ),
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("name", models.CharField(help_text="The name of the registration.", max_length=500)),
                ("reference_pk", models.IntegerField(help_text="The reference primary key from the Aurora system.")),
                (
                    "country_office",
                    models.ForeignKey(
                        help_text="The country office associated with this record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="country_workspace.office",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The program associated with this record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="country_workspace.program",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
