# Generated by Django 5.1.2 on 2024-10-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="flex_files",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individual",
            name="flex_files",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
