# Generated by Django 5.1.3 on 2025-02-21 12:20

import django.db.models.deletion
import strategy_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0001_initial"),
        ("hope_flex_fields", "0013_fielddefinition_validated_alter_datachecker_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asyncjob",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="country_workspace.program",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="active",
            field=models.BooleanField(
                default=False, help_text="Whether the program is active. Only active program are visible in the UI"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="beneficiary_validator",
            field=strategy_field.fields.StrategyField(
                blank=True,
                default="country_workspace.validators.registry.NoopValidator",
                help_text="Validator to use to validate the whole Household",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="household_checker",
            field=models.ForeignKey(
                blank=True,
                help_text="Checker to use with Household's records",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="hope_flex_fields.datachecker",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="individual_checker",
            field=models.ForeignKey(
                blank=True,
                help_text="Checker to use with Individual's records",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="hope_flex_fields.datachecker",
            ),
        ),
    ]
