# Generated by Django 5.1.2 on 2024-10-23 15:13

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0002_household_flex_files_individual_flex_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncJob",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", concurrency.fields.AutoIncVersionField(default=0, help_text="record revision number")),
                (
                    "curr_async_result_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Current (active) AsyncResult is",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "last_async_result_id",
                    models.CharField(
                        blank=True, editable=False, help_text="Latest executed AsyncResult is", max_length=36, null=True
                    ),
                ),
                ("celery_history", models.JSONField(blank=True, default=dict, editable=False)),
                ("celery_result", models.CharField(blank=True, default="", editable=False, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("BULK_UPDATE_HH", "Bulk Update Hh"), ("BULK_UPDATE_IND", "Bulk Update Ind")],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="updates")),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="country_workspace.batch",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="country_workspace.program"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "queue", "terminate", "inspect", "revoke"),
            },
        ),
    ]
