# Generated by Django 5.1.3 on 2025-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0002_alter_asyncjob_program_alter_program_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KoboAsset",
            fields=[
                ("uid", models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(editable=False, max_length=128, null=True)),
                ("programs", models.ManyToManyField(to="country_workspace.program")),
            ],
        ),
    ]
