# Generated by Django 5.1.3 on 2025-03-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0003_koboasset"),
    ]

    operations = [
        migrations.CreateModel(
            name="KoboSubmission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_uid", models.CharField(db_index=True, editable=False, max_length=32)),
                ("submission_id", models.IntegerField(editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name="KoboAsset",
        ),
    ]
