# Generated by Django 5.1.2 on 2024-11-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0003_koboasset_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="koboasset",
            name="name",
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
