# Generated by Django 5.1.3 on 2025-03-13 09:04

from django.db import migrations, models
from country_workspace.storages import MEDIA_STORAGE


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0004_kobosubmission_delete_koboasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asyncjob",
            name="file",
            field=models.FileField(blank=True, null=True, storage=MEDIA_STORAGE, upload_to="updates"),
        ),
    ]
