# Generated by Django 5.1.2 on 2024-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0004_koboasset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="koboasset",
            name="uid",
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
