# Generated by Django 5.1.7 on 2025-03-18 12:26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0005_alter_asyncjob_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="kobo_country_code",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
