# Generated by Django 5.1.7 on 2025-03-18 12:26
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def migrate_data(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    office_model = apps.get_model("country_workspace", "Office")
    for obj in office_model.objects.filter(country_iso_code=None):
        obj.country_iso_code = "AFG"
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0005_alter_asyncjob_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="country_iso_code",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="office",
            name="country_iso_code",
            field=models.CharField(max_length=3),
        ),
    ]
