# Generated by Django 5.1.3 on 2025-03-04 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0005_alter_asyncjob_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="individual",
            options={
                "permissions": (
                    ("validate_beneficiary", "Can validate Beneficiary Records"),
                    ("mass_update_beneficiary", "Can Mass update Beneficiary Records"),
                    ("regex_update_beneficiary", "Can Mass update Beneficiary Records"),
                    ("export_beneficiary", "Can Export Beneficiary Records"),
                    ("push_beneficiary_to_hope", "Can Push Beneficiary Records To HOPE core"),
                )
            },
        ),
    ]
