# Generated by Django 5.1.2 on 2024-11-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0005_alter_koboasset_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kobosubmission",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="KoboQuestion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(editable=False, max_length=128, null=True)),
                ("labels", models.JSONField(default=list)),
                (
                    "asset",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="country_workspace.koboasset"),
                ),
            ],
        ),
    ]
