# Generated by Django 5.1.2 on 2024-11-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("country_workspace", "0006_alter_kobosubmission_data_koboquestion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="koboquestion",
            unique_together={("asset", "key")},
        ),
    ]
