# Generated by Django 5.1.7 on 2025-03-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0006_office_kobo_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="individual_columns",
            field=models.TextField(default="name\nid", help_text="Columns to display i the Admin table"),
        ),
    ]
