# Generated by Django 5.1.7 on 2025-03-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0008_alter_individual_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "hope_id",
                    models.CharField(
                        blank=True, help_text="Unique ID from HOPE", max_length=100, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Name of the beneficiary group", max_length=255, unique=True)),
                ("group_label", models.CharField(help_text="Label for the group", max_length=255)),
                ("group_label_plural", models.CharField(help_text="Plural label for the group", max_length=255)),
                ("member_label", models.CharField(help_text="Label for the member", max_length=255)),
                ("member_label_plural", models.CharField(help_text="Plural label for the member", max_length=255)),
                (
                    "master_detail",
                    models.BooleanField(default=True, help_text="Indicates if this is a master-detail group"),
                ),
            ],
            options={
                "verbose_name": "Beneficiary Group",
                "verbose_name_plural": "Beneficiary Groups",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="asyncjob",
            options={
                "permissions": (("debug_job", "Can debug background jobs"),),
                "verbose_name": "Async Job",
                "verbose_name_plural": "Async Jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="batch",
            options={"verbose_name": "Batch", "verbose_name_plural": "Batches"},
        ),
        migrations.AlterField(
            model_name="office",
            name="kobo_country_code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="beneficiary_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Beneficiary group to which this program belongs",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="country_workspace.beneficiarygroup",
            ),
        ),
    ]
