# Generated by Django 5.1.7 on 2025-04-01 12:50

import concurrency.fields
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0009_beneficiarygroup_alter_asyncjob_options_and_more"),
        ("pghistory", "0006_delete_aggregateevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("last_checked", models.DateTimeField(blank=True, default=None, null=True)),
                ("errors", models.JSONField(blank=True, default=dict, editable=False)),
                ("flex_fields", models.JSONField(blank=True, default=dict)),
                ("flex_files", models.BinaryField(blank=True, null=True)),
                ("removed", models.BooleanField(default=False, verbose_name="Removed")),
                ("checksum", models.CharField(blank=True, max_length=300, null=True, verbose_name="checksum")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("system_fields", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndividualFlexFieldsFlexFilesRemovedEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("flex_fields", models.JSONField(blank=True, default=dict)),
                ("flex_files", models.BinaryField(blank=True, null=True)),
                ("removed", models.BooleanField(default=False, verbose_name="Removed")),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="household",
            trigger=pgtrigger.compiler.Trigger(
                name="updates_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."flex_fields" IS DISTINCT FROM (NEW."flex_fields") OR OLD."flex_files" IS DISTINCT FROM (NEW."flex_files") OR OLD."removed" IS DISTINCT FROM (NEW."removed"))',
                    func='INSERT INTO "country_workspace_householdevent" ("batch_id", "checksum", "errors", "flex_fields", "flex_files", "id", "last_checked", "last_modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed", "system_fields", "version") VALUES (NEW."batch_id", NEW."checksum", NEW."errors", NEW."flex_fields", NEW."flex_files", NEW."id", NEW."last_checked", NEW."last_modified", NEW."name", _pgh_attach_context(), NOW(), \'updates\', NEW."id", NEW."removed", NEW."system_fields", NEW."version"); RETURN NULL;',
                    hash="41deb29d89baf14da071db54574a04c335785ea6",
                    operation="UPDATE",
                    pgid="pgtrigger_updates_update_f353b",
                    table="country_workspace_household",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="individual",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "country_workspace_individualflexfieldsflexfilesremovedevent" ("flex_fields", "flex_files", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed") VALUES (NEW."flex_fields", NEW."flex_files", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."removed"); RETURN NULL;',
                    hash="546ae6ba96473bd4d36645086336ffd8ac4dddb0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_3c11b",
                    table="country_workspace_individual",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="individual",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."flex_fields" IS DISTINCT FROM (NEW."flex_fields") OR OLD."flex_files" IS DISTINCT FROM (NEW."flex_files") OR OLD."removed" IS DISTINCT FROM (NEW."removed"))',
                    func='INSERT INTO "country_workspace_individualflexfieldsflexfilesremovedevent" ("flex_fields", "flex_files", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed") VALUES (NEW."flex_fields", NEW."flex_files", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."removed"); RETURN NULL;',
                    hash="08e91e85897e2824d36900cd8cf56593b9313078",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_6a215",
                    table="country_workspace_individual",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="householdevent",
            name="batch",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="country_workspace.batch",
            ),
        ),
        migrations.AddField(
            model_name="householdevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="householdevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="country_workspace.household",
            ),
        ),
        migrations.AddField(
            model_name="individualflexfieldsflexfilesremovedevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="individualflexfieldsflexfilesremovedevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="flex_fields_flex_files_removed_events",
                to="country_workspace.individual",
            ),
        ),
    ]
