# Generated by Django 5.1.7 on 2025-04-21 14:57

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0010_householdevent_individualevent_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="household",
            name="updates_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="individual",
            name="updates_update",
        ),
        migrations.RemoveField(
            model_name="program",
            name="active",
        ),
        migrations.AlterField(
            model_name="program",
            name="individual_columns",
            field=models.TextField(default="name\nid", help_text="Columns to display in the Admin table"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="household",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."flex_fields" IS DISTINCT FROM (NEW."flex_fields") OR OLD."flex_files" IS DISTINCT FROM (NEW."flex_files") OR OLD."removed" IS DISTINCT FROM (NEW."removed"))',
                    func='INSERT INTO "country_workspace_householdevent" ("batch_id", "checksum", "errors", "flex_fields", "flex_files", "id", "last_checked", "last_modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed", "system_fields", "version") VALUES (NEW."batch_id", NEW."checksum", NEW."errors", NEW."flex_fields", NEW."flex_files", NEW."id", NEW."last_checked", NEW."last_modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."removed", NEW."system_fields", NEW."version"); RETURN NULL;',
                    hash="8ecf3de9db1d0a404013f2d873e0f061d7d00111",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c2d37",
                    table="country_workspace_household",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="individual",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."flex_fields" IS DISTINCT FROM (NEW."flex_fields") OR OLD."flex_files" IS DISTINCT FROM (NEW."flex_files") OR OLD."removed" IS DISTINCT FROM (NEW."removed"))',
                    func='INSERT INTO "country_workspace_individualevent" ("batch_id", "checksum", "errors", "flex_fields", "flex_files", "household_id", "id", "last_checked", "last_modified", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "removed", "system_fields", "version") VALUES (NEW."batch_id", NEW."checksum", NEW."errors", NEW."flex_fields", NEW."flex_files", NEW."household_id", NEW."id", NEW."last_checked", NEW."last_modified", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."removed", NEW."system_fields", NEW."version"); RETURN NULL;',
                    hash="75976263954d18b98b4e9bdd634a3e7db04f8c60",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_6a215",
                    table="country_workspace_individual",
                    when="AFTER",
                ),
            ),
        ),
    ]
