# Generated by Django 5.1.7 on 2025-05-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0013_country_iso_code3"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="enabled",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Is this office enabled in the workspace?"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="enabled",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Is this program enabled in the workspace?"
            ),
        ),
        migrations.AlterField(
            model_name="office",
            name="active",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Is this office active in the HOPE core?"
            ),
        ),
    ]
