# Generated by Django 5.2.1 on 2025-06-11 06:45

import concurrency.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0014_office_enabled_program_enabled_alter_office_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rdp",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("PENDING", "Pending"), ("SUCCESS", "Success"), ("FAILURE", "FAILURE")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("push_date", models.DateTimeField(auto_now=True)),
                (
                    "country_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="country_workspace.office",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="country_workspace.program",
                    ),
                ),
                (
                    "pushed_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Registration Data Push",
                "verbose_name_plural": "Registration Data Pushes",
                "unique_together": {("program", "name")},
            },
        ),
        migrations.AddField(
            model_name="asyncjob",
            name="rdp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="country_workspace.rdp",
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="rdp",
            field=models.ManyToManyField(blank=True, related_name="%(class)ss", to="country_workspace.rdp"),
        ),
        migrations.AddField(
            model_name="individual",
            name="rdp",
            field=models.ManyToManyField(blank=True, related_name="%(class)ss", to="country_workspace.rdp"),
        ),
    ]
