# Generated by Django 5.2.1 on 2025-06-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "country_workspace",
            "0014_office_enabled_program_enabled_alter_office_active",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asyncjob",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="updates"),
        ),
    ]
