# Generated by Django 5.2.3 on 2025-06-18 14:42

import storages.backends.azure_storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0015_alter_asyncjob_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asyncjob",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.azure_storage.AzureStorage(),
                upload_to="updates",
            ),
        ),
    ]
