# Generated by Django 5.2.3 on 2025-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0017_rdp_asyncjob_rdp_household_rdp_individual_rdp"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdp",
            name="hope_rdi_id",
            field=models.CharField(
                editable=False, help_text="RDI unique ID within the HOPE core.", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("PENDING", "Pending"), ("SUCCESS", "Success"), ("FAILURE", "Failure")],
                max_length=10,
                null=True,
            ),
        ),
    ]
