# Generated by Django 5.2.3 on 2025-06-26 12:44

import concurrency.fields
import country_workspace.validators.mapping
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0017_rdp_asyncjob_rdp_household_rdp_individual_rdp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdp",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("PENDING", "Pending"), ("SUCCESS", "Success"), ("FAILURE", "Failure")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MappingImporter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "rules",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Field mapping rules (one per line). Format: `sheet_name:field_name=datachecker name:field_name`. Example: Individuals:gender=HOPE Individual core:sex",
                        validators=[country_workspace.validators.mapping.FieldMappingRulesValidator()],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="country_workspace.office",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="country_workspace.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapping Importer",
                "verbose_name_plural": "Mapping Importers",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        fields=("name",),
                        name="unique_non_empty_name",
                        violation_error_message="A mapping importer with this name already exists.",
                    )
                ],
            },
        ),
    ]
