# Generated by Django 5.2.3 on 2025-06-24 08:23

import country_workspace.validators.mapping
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0017_rdp_asyncjob_rdp_household_rdp_individual_rdp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdp",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("PENDING", "Pending"), ("SUCCESS", "Success"), ("FAILURE", "Failure")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MappingProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ANY", "Any Source"),
                            ("AURORA", "Aurora REST API"),
                            ("KOBO", "Kobo REST API"),
                            ("XLSX", "Excel Files"),
                        ],
                        db_index=True,
                        default="ANY",
                        max_length=50,
                    ),
                ),
                (
                    "import_schema",
                    models.CharField(
                        choices=[
                            ("ANY", "Any Structure"),
                            ("HH_IND", "Household + Individuals"),
                            ("PEOPLE", "People only"),
                        ],
                        db_index=True,
                        default="ANY",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="Parent profile for inheritance",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="country_workspace.mappingprofile",
                    ),
                ),
                (
                    "program",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Programs this profile is associated with",
                        related_name="%(class)ss",
                        to="country_workspace.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapping Profile",
                "verbose_name_plural": "Mapping Profiles",
            },
        ),
        migrations.CreateModel(
            name="FieldMappingRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Updated at")),
                ("name", models.CharField(max_length=255)),
                (
                    "expression",
                    models.TextField(
                        blank=True,
                        help_text="JMESPath expression that returns object with new/modified fields only",
                        validators=[country_workspace.validators.mapping.JMESPathValidator()],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100, help_text="Order of execution for the rule (lower is earlier)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mapping profile this rule belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="country_workspace.mappingprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Mapping Rule",
                "verbose_name_plural": "Field Mapping Rules",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="mappingprofile",
            index=models.Index(
                fields=["source_type", "import_schema", "is_active"], name="country_wor_source__3c14cc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mappingprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("pk")), _negated=True),
                name="mapping_profile_not_self_parent",
                violation_error_message="Profile cannot be its own parent",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldmappingrule",
            index=models.Index(fields=["profile", "is_active", "order"], name="country_wor_profile_ac2a1d_idx"),
        ),
        migrations.AddConstraint(
            model_name="fieldmappingrule",
            constraint=models.UniqueConstraint(
                fields=("profile", "name"),
                name="unique_rule_name_per_profile",
                violation_error_message="Rule name must be unique within profile",
            ),
        ),
    ]
