# Generated by Django 5.2.3 on 2025-07-04 13:18

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0018_rdp_hope_rdi_id_alter_rdp_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSerializer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("name", models.SlugField(max_length=64, unique=True)),
                ("code", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="program",
            name="serializer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="country_workspace.dataserializer"
            ),
        ),
    ]
