# Generated by Django 5.2.3 on 2025-07-10 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0019_mappingimporter"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rdp",
            unique_together={("push_date", "name")},
        ),
    ]
