# Generated by Django 5.2.3 on 2025-07-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0019_dataserializer_program_serializer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="serializer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="country_workspace.dataserializer",
            ),
        ),
    ]
