# Generated by Django 5.2.3 on 2025-07-10 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0019_mappingimporter"),
        ("country_workspace", "0020_alter_program_serializer"),
    ]

    operations = []
