# Generated by Django 5.2.3 on 2025-07-14 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0020_alter_rdp_unique_together"),
        ("country_workspace", "0021_merge_20250710_1203"),
    ]

    operations = []
