# Generated by Django 5.2.3 on 2025-08-06 08:52
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("country_workspace", "0022_remove_household_update_update_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="individual",
            options={"verbose_name": "Individual"},
        ),
        AddIndexConcurrently(
            model_name="individual",
            index=models.Index(fields=["batch", "removed"], name="country_workspace_individual_batch_removed_idx"),
        ),
        AddIndexConcurrently(
            model_name="individual",
            index=models.Index(fields=["name"], name="country_workspace_individual_name_idx"),
        ),
        AddIndexConcurrently(
            model_name="individual",
            index=models.Index(fields=["batch", "name"], name="country_workspace_individual_batch_name_idx"),
        ),
    ]
