# Generated by Django 5.2.3 on 2025-10-24 04:32
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models import Func, F, Value, CharField, JSONField
from django.db.models.functions import Cast


def set_household_id_in_flex_fields(apps: Apps, _: BaseDatabaseSchemaEditor) -> None:
    Household = apps.get_model("country_workspace", "Household")
    (
        Household.objects.filter(flex_fields__household_id="").update(
            flex_fields=Func(
                F("flex_fields"),
                Value("{household_id}"),
                Cast(Cast(F("id"), CharField()), JSONField()),
                function="jsonb_set",
            )
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0023_alter_individual_options_and_more"),
    ]

    operations = [
        migrations.RunPython(set_household_id_in_flex_fields, reverse_code=migrations.RunPython.noop),
    ]
