# Generated by Django 5.2.3 on 2025-10-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0023_alter_individual_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="areatype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="office",
            name="countries",
            field=models.ManyToManyField(blank=True, related_name="%(class)ss", to="country_workspace.country"),
        ),
        migrations.AddIndex(
            model_name="areatype",
            index=models.Index(fields=["country", "area_level"], name="country_wor_country_1d6878_idx"),
        ),
        migrations.AddConstraint(
            model_name="areatype",
            constraint=models.UniqueConstraint(
                fields=("country", "area_level", "name"), name="unique_area_type_per_country_level_name"
            ),
        ),
    ]
