# Generated by Django 5.2.3 on 2025-09-04 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0023_alter_individual_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="beneficiarygroup",
            options={
                "ordering": ("name",),
                "permissions": [
                    ("adminactions_validate_beneficiarygroup", "Can bulkupdate Beneficiary Group (adminactions)"),
                    ("adminactions_regex_update_beneficiarygroup", "Can bulkupdate Beneficiary Group (adminactions)"),
                    ("adminactions_push_to_hope_beneficiarygroup", "Can bulkupdate Beneficiary Group (adminactions)"),
                ],
                "verbose_name": "Beneficiary Group",
                "verbose_name_plural": "Beneficiary Groups",
            },
        ),
    ]
