# Generated by Django 5.2.8 on 2025-11-07 09:21
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("country_workspace", "0026_alter_program_household_checker_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="areatype",
            index=models.Index(
                fields=["tree_id", "lft"],
                name="country_workspace_areatypef190",
            ),
        ),
    ]
