# Generated by Django 5.2.8 on 2025-11-11 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0027_areatype_country_workspace_areatypef190"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KoboSubmission",
        ),
    ]
