# Generated by Django 5.2.8 on 2025-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("country_workspace", "0028_delete_kobosubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="synclog",
            name="name",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="synclog",
            unique_together={("name", "content_type", "object_id")},
        ),
    ]
