# Generated by Django 5.2.8 on 2025-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0029_synclog_name_alter_synclog_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synclog",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
