# Generated by Django 5.2.3 on 2025-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0031_add_parse_name_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="system_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Internal metadata (e.g. "default_fields" for household/individual defaults).',
            ),
        ),
    ]
