# Generated by Django 5.2.8 on 2025-12-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0033_update_mapping_importer_with_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdp",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
