# Generated by Django 5.2.9 on 2025-12-18 10:44

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def fill_office(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    MappingImporter = apps.get_model("country_workspace", "MappingImporter")
    Office = apps.get_model("country_workspace", "Office")
    default_office = Office.objects.first()
    MappingImporter.objects.filter(office__isnull=True).update(office=default_office)


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0035_alter_rdp_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="individual",
            options={"verbose_name": "Individual"},
        ),
        migrations.AlterModelOptions(
            name="office",
            options={"ordering": ["name"]},
        ),
        migrations.RunPython(fill_office, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="mappingimporter",
            name="office",
            field=models.ForeignKey(
                help_text="Business Area (Office) this mapping belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapping_importers",
                to="country_workspace.office",
            ),
        ),
    ]
