# Generated by Django 5.2.9 on 2025-12-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0035_alter_rdp_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="individual",
            options={"verbose_name": "Individual"},
        ),
        migrations.AlterModelOptions(
            name="office",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="mappingimporter",
            name="office",
            field=models.ForeignKey(
                help_text="Business Area (Office) this mapping belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapping_importers",
                to="country_workspace.office",
            ),
        ),
    ]
