# Generated by Django 5.2.3 on 2025-12-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("country_workspace", "0036_alter_individual_options_alter_office_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="synclog",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="synclog",
            constraint=models.UniqueConstraint(
                fields=("name", "content_type", "object_id"), name="unique_synclog_per_object"
            ),
        ),
        migrations.AddConstraint(
            model_name="synclog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", True), ("object_id__isnull", True)),
                fields=("content_type",),
                name="unique_synclog_global_per_content_type",
            ),
        ),
    ]
