# Generated by Django 5.2.9 on 2025-12-22 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0036_alter_individual_options_alter_office_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rdp",
            options={
                "permissions": [("reset_rdp", "Can reset RDP")],
                "verbose_name": "Registration Data Push",
                "verbose_name_plural": "Registration Data Pushes",
            },
        ),
    ]
