# Generated by Django 5.2.9 on 2025-12-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0039_add_originating_id_to_validable"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="hh_alien_columns_to_ignore",
            field=models.TextField(blank=True, default=None, help_text="Alien fields to ignore", null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="ind_alien_columns_to_ignore",
            field=models.TextField(blank=True, default=None, help_text="Alien fields to ignore", null=True),
        ),
    ]
