# Generated by Django 5.2.8 on 2025-12-29 08:53

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0039_alter_synclog_unique_together_add_constraints"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="household",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="individual",
            name="update_update",
        ),
        migrations.AddField(
            model_name="household",
            name="originating_id",
            field=models.CharField(blank=True, verbose_name="Originating ID"),
        ),
        migrations.AddField(
            model_name="householdevent",
            name="originating_id",
            field=models.CharField(blank=True, verbose_name="Originating ID"),
        ),
        migrations.AddField(
            model_name="individual",
            name="originating_id",
            field=models.CharField(blank=True, verbose_name="Originating ID"),
        ),
        migrations.AddField(
            model_name="individualevent",
            name="originating_id",
            field=models.CharField(blank=True, verbose_name="Originating ID"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="household",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."flex_fields" IS DISTINCT FROM (NEW."flex_fields") OR OLD."flex_files" IS DISTINCT FROM (NEW."flex_files") OR OLD."removed" IS DISTINCT FROM (NEW."removed"))',
                    func='INSERT INTO "country_workspace_householdevent" ("batch_id", "checksum", "errors", "flex_fields", "flex_files", "id", "last_checked", "last_modified", "name", "originating_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_data", "removed", "system_fields", "version") VALUES (NEW."batch_id", NEW."checksum", NEW."errors", NEW."flex_fields", NEW."flex_files", NEW."id", NEW."last_checked", NEW."last_modified", NEW."name", NEW."originating_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."raw_data", NEW."removed", NEW."system_fields", NEW."version"); RETURN NULL;',
                    hash="e8873fd19a1fa0d83d3f501b83c3632188ffea68",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c2d37",
                    table="country_workspace_household",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="individual",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."flex_fields" IS DISTINCT FROM (NEW."flex_fields") OR OLD."flex_files" IS DISTINCT FROM (NEW."flex_files") OR OLD."removed" IS DISTINCT FROM (NEW."removed"))',
                    func='INSERT INTO "country_workspace_individualevent" ("batch_id", "checksum", "errors", "flex_fields", "flex_files", "household_id", "id", "last_checked", "last_modified", "name", "originating_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_data", "removed", "system_fields", "version") VALUES (NEW."batch_id", NEW."checksum", NEW."errors", NEW."flex_fields", NEW."flex_files", NEW."household_id", NEW."id", NEW."last_checked", NEW."last_modified", NEW."name", NEW."originating_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."raw_data", NEW."removed", NEW."system_fields", NEW."version"); RETURN NULL;',
                    hash="f2436479c554831212c6e73e50b6031757f2ca94",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_6a215",
                    table="country_workspace_individual",
                    when="AFTER",
                ),
            ),
        ),
    ]
