# Generated by Django 5.2.9 on 2026-01-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0040_add_originating_id_to_validable"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rdp",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="rdp",
            constraint=models.UniqueConstraint(fields=("push_date", "name"), name="uniq_rdp_push_date_name"),
        ),
        migrations.AddConstraint(
            model_name="rdp",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("program",),
                name="uniq_pending_rdp_per_program",
                violation_error_message="There is already an active (PENDING) RDP for this program.",
            ),
        ),
    ]
