# Generated by Django 5.2.9 on 2026-01-20 10:04

import country_workspace.validators.mapping
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0041_create_transformer_and_migrate_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transformer",
            name="value_transformations",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Value transformation rules (JavaScript). Example: `function transform(record) { record['sex'] = 'Male'; return record; }`",
                validators=[country_workspace.validators.mapping.ValueTransformationRulesValidator()],
            ),
        ),
    ]
