# Generated by Django 5.2.9 on 2026-01-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0041_alter_rdp_unique_together_alter_rdp_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdp",
            name="dedup_run_state",
            field=models.CharField(
                choices=[("NOT_RUN", "Not run yet"), ("SCHEDULED", "Scheduled"), ("APPROVED", "Approved")],
                default="NOT_RUN",
                help_text="Internal deduplication lifecycle.",
                max_length=15,
            ),
        ),
    ]
