# Generated by Django 5.2.11 on 2026-02-09 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0043_batch_status_and_kobo_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ("name",),
                "permissions": (("sync_area", "Can sync area"),),
                "verbose_name_plural": "Areas",
            },
        ),
        migrations.AlterModelOptions(
            name="areatype",
            options={"permissions": (("sync_areatype", "Can sync area type"),), "verbose_name_plural": "Area Types"},
        ),
        migrations.AlterModelOptions(
            name="beneficiarygroup",
            options={
                "ordering": ("name",),
                "permissions": (("sync_beneficiarygroup", "Can sync beneficiary group"),),
                "verbose_name": "Beneficiary Group",
                "verbose_name_plural": "Beneficiary Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ("name",),
                "permissions": (("sync_country", "Can sync country"),),
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterModelOptions(
            name="office",
            options={"ordering": ["name"], "permissions": (("sync_office", "Can sync office"),)},
        ),
        migrations.AlterModelOptions(
            name="program",
            options={
                "permissions": (
                    ("import_program_data", "Can Import beneficiaries"),
                    ("sync_program", "Can sync program"),
                ),
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
            },
        ),
    ]
