# Generated by Django 5.2.9 on 2026-01-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0044_rdp_dedup_run_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdp",
            name="deduplication_set_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
