# Generated by Django 5.2.9 on 2026-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0045_rdp_deduplication_set_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="biometric_deduplication_enabled",
            field=models.BooleanField(default=False, help_text="Is biometric deduplication enabled for this program?"),
        ),
    ]
