# Generated by Django 5.2.11 on 2026-02-14 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0047_program_biometric_deduplication_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="synclog",
            options={"permissions": [("can_synchronize", "Can synchronize objects with HOPE")]},
        ),
    ]
