# Generated by Django 5.2.11 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0048_alter_synclog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="alien_validation_enabled",
            field=models.BooleanField(default=True, help_text="Should alien-field validation run for this programme?"),
        ),
    ]
