# Generated by Django 5.2.11 on 2026-03-20 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0050_alter_rdp_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rdp",
            options={
                "permissions": [
                    ("reset_rdp", "Can reset RDP"),
                    ("create_rdp", "Can create RDP from selected beneficiaries"),
                    ("deduplicate_rdp", "Can run RDP deduplication"),
                    ("reject_deduplication_set", "Can reject deduplication set"),
                    ("push_rdp_to_hope", "Can push RDP to HOPE"),
                ],
                "verbose_name": "Registration Data Push",
                "verbose_name_plural": "Registration Data Pushes",
            },
        ),
    ]
