# Generated by Django 5.2.11 on 2026-03-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0051_alter_rdp_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdp",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the parent RDP if this RDP was created as a clone of another.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="country_workspace.rdp",
            ),
        ),
    ]
