# Generated by Django 5.2.11 on 2026-04-06 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0052_rdp_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rdp",
            name="dedup_run_state",
        ),
    ]
