# Generated by Django 5.2.13 on 2026-04-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0053_remove_rdp_dedup_run_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdp",
            name="deduplication_snapshots",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rdp",
            name="is_dedup_settings_locked",
            field=models.BooleanField(
                default=False,
                help_text="Blocks changes to program deduplication settings after deduplication has been started for this RDP.",
            ),
        ),
    ]
