# Generated by Django 5.2.11 on 2026-05-05 13:42

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0053_remove_rdp_dedup_run_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True, editable=False)),
                ("version", concurrency.fields.IntegerVersionField(db_index=True, verbose_name="Version")),
                ("hope_id", models.BigIntegerField(editable=False, unique=True)),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
    ]
