# Generated by Django 5.2.13 on 2026-04-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0053_remove_rdp_dedup_run_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdp",
            name="deduplication_snapshots",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rdp",
            name="is_deduplication_started",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the deduplication process has been started for this RDP."
            ),
        ),
    ]
