# Generated by Django 5.2.14 on 2026-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_workspace', '0054_rdp_deduplication_snapshots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='source',
            field=models.CharField(blank=True, choices=[('RDI', 'Rdi file'), ('AURORA', 'Aurora'), ('KOBO', 'Kobo'), ('ONA', 'ONA / INFORM')], max_length=255, null=True),
        ),
    ]
