# Generated by Django 5.2.14 on 2026-06-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0055_remove_rdp_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rdp",
            name="deduplication_snapshots",
        ),
        migrations.AddField(
            model_name="rdp",
            name="operation_log",
            field=models.JSONField(
                blank=True, default=list, help_text="Append-only chronological log of RDP operations."
            ),
        ),
    ]
