# Generated by Django 5.2.14 on 2026-06-05 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0056_rdp_uniq_rdp_hope_rdi_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                ("key", models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ("grant_type", models.CharField(choices=[("HOPE_RDI_CALLBACK", "HOPE RDI Callback")], max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("offices", models.ManyToManyField(related_name="api_tokens", to="country_workspace.office")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_to__isnull", True), ("valid_to__gt", models.F("valid_from")), _connector="OR"
                        ),
                        name="api_token_valid_period",
                        violation_error_message="Valid to must be later than valid from.",
                    )
                ],
            },
        ),
    ]
