# Generated by Django 5.2.14 on 2026-06-08 08:36

import django.db.models.deletion
import django.utils.timezone
import hope_api_auth.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0056_rdp_uniq_rdp_hope_rdi_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                ("key", models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name="Key")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("allowed_ips", models.CharField(blank=True, max_length=200, null=True, verbose_name="IPs")),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "grants",
                    hope_api_auth.fields.ChoiceArrayField(base_field=models.CharField(max_length=255), size=None),
                ),
                ("offices", models.ManyToManyField(related_name="api_tokens", to="country_workspace.office")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
