# Generated by Django 5.2.14 on 2026-07-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0058_rdp_dedup_pending_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rdp",
            name="uniq_open_rdp_per_program",
        ),
        migrations.AddConstraint(
            model_name="rdp",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("PENDING", "FAILURE", "DEDUP_PENDING", "PUSH_PENDING"))),
                fields=("program",),
                name="uniq_non_terminal_rdp_per_program",
                violation_error_message="There is already an unfinished RDP for this program.",
            ),
        ),
    ]
