# Generated by Django 5.2.14 on 2026-08-23 18:16

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0060_remove_individual_update_update_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="individual",
            name="update_update",
        ),
        migrations.AddField(
            model_name="individual",
            name="blob_hashes",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="individualevent",
            name="blob_hashes",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="individual",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."flex_fields" IS DISTINCT FROM (NEW."flex_fields") OR OLD."flex_files" IS DISTINCT FROM (NEW."flex_files") OR OLD."removed" IS DISTINCT FROM (NEW."removed"))',
                    func='INSERT INTO "country_workspace_individualevent" ("batch_id", "blob_hashes", "checksum", "errors", "flex_fields", "flex_files", "household_id", "id", "identity_hash", "last_checked", "last_modified", "name", "originating_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "raw_data", "removed", "system_fields", "version") VALUES (NEW."batch_id", NEW."blob_hashes", NEW."checksum", NEW."errors", NEW."flex_fields", NEW."flex_files", NEW."household_id", NEW."id", NEW."identity_hash", NEW."last_checked", NEW."last_modified", NEW."name", NEW."originating_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."raw_data", NEW."removed", NEW."system_fields", NEW."version"); RETURN NULL;',
                    hash="0b7d96eb22d18cc3aaea9ace77951140e48b982a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_6a215",
                    table="country_workspace_individual",
                    when="AFTER",
                ),
            ),
        ),
    ]
