# Generated by Django 5.2.14 on 2026-09-04 07:09

import country_workspace.models.rdp
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0062_remove_rdp_uniq_open_rdp_per_program_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdp",
            name="country_office",
            field=models.ForeignKey(
                help_text="Country office associated with this RDP.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="country_workspace.office",
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="deduplication_set_id",
            field=models.UUIDField(
                blank=True,
                help_text="Unique identifier of the deduplication set created in DedupEngine for this RDP.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="hope_rdi_id",
            field=models.CharField(
                editable=False,
                help_text="Unique identifier of the RDI in HOPE associated with this RDP.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="is_dedup_settings_locked",
            field=models.BooleanField(
                default=False,
                help_text="Whether program-level deduplication settings are locked while this RDP is being deduplicated.",
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of this Registration Data Push.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="operation_log",
            field=models.JSONField(
                blank=True, default=list, help_text="Chronological log of operations recorded for this RDP."
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="program",
            field=models.ForeignKey(
                help_text="Program associated with this RDP.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="country_workspace.program",
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="push_date",
            field=models.DateTimeField(auto_now_add=True, help_text="Date and time when this RDP was created."),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="pushed_by",
            field=models.ForeignKey(
                help_text="User who initiated this RDP.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rdp",
            name="status",
            field=models.CharField(
                blank=True,
                choices=country_workspace.models.rdp.get_rdp_status_choices,
                default="PENDING",
                help_text="Current stage of this RDP in the processing workflow.",
                max_length=15,
            ),
        ),
    ]
