# Generated by Django 5.2.14 on 2026-09-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0063_alter_rdp_country_office_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rdp",
            name="uniq_non_terminal_rdp_per_program",
        ),
        migrations.AddField(
            model_name="rdp",
            name="deduplication_findings_count",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="Number of duplicate findings reported by DedupEngine for this RDP.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rdp",
            name="duplicate_individuals",
            field=models.ManyToManyField(
                blank=True,
                help_text="Individuals marked as duplicates by DedupEngine for this RDP.",
                related_name="duplicate_rdps",
                to="country_workspace.individual",
            ),
        ),
        migrations.AddConstraint(
            model_name="rdp",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("PENDING", "FAILURE", "DEDUP_PENDING", "REVIEW_PENDING", "PUSH_PENDING"))
                ),
                fields=("program",),
                name="uniq_non_terminal_rdp_per_program",
                violation_error_message="There is already an unfinished RDP for this program.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="rdp",
            name="uniq_rdp_push_date_name",
            constraint=models.UniqueConstraint(
                fields=("push_date", "name"),
                name="uniq_rdp_push_date_name",
                violation_error_message="An RDP with this name and push date already exists.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="rdp",
            name="rdp_push_attempt_state_consistent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("push_attempt_id__isnull", False), ("status", "PUSH_PENDING")),
                    models.Q(models.Q(("status", "PUSH_PENDING"), _negated=True), ("push_attempt_id__isnull", True)),
                    _connector="OR",
                ),
                name="rdp_push_attempt_state_consistent",
                violation_error_message="Push attempt must be set only while the RDP push is in progress.",
            ),
        ),
    ]
