# Generated by Django 5.2.14 on 2026-08-23 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0063_blob_hashes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rdp",
            options={
                "permissions": [
                    ("cancel_rdp", "Can cancel RDP"),
                    ("create_rdp", "Can create RDP from selected beneficiaries"),
                    ("deduplicate_rdp", "Can run RDP deduplication"),
                    ("push_rdp_to_hope", "Can push RDP to HOPE"),
                    ("reset_rdp", "Can reset RDP"),
                    ("run_ocr_rdp", "Can run RDP OCR"),
                ],
                "verbose_name": "Registration Data Push",
                "verbose_name_plural": "Registration Data Pushes",
            },
        ),
        migrations.CreateModel(
            name="OcrRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("batch_total", models.PositiveIntegerField(default=0)),
                ("received_batch_ids", models.JSONField(blank=True, default=list)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rdp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_run",
                        to="country_workspace.rdp",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR run",
                "verbose_name_plural": "OCR runs",
            },
        ),
    ]
