# Generated by Django 5.2.14 on 2026-09-23 09:01

import concurrency.fields
import country_workspace.models.rdp_operation
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0064_remove_rdp_uniq_non_terminal_rdp_per_program_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RdpOperation",
            fields=[
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier of this RDP operation and its external correlation ID.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=country_workspace.models.rdp_operation.get_rdp_operation_type_choices,
                        help_text="Type of operation to execute.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=country_workspace.models.rdp_operation.get_rdp_operation_status_choices,
                        default="PENDING",
                        help_text="Current execution status of this operation.",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Configuration captured when this operation was created."
                    ),
                ),
                ("error", models.JSONField(blank=True, default=dict, help_text="Current execution error, if any.")),
                (
                    "log",
                    models.JSONField(
                        blank=True, default=list, help_text="Chronological execution log for this operation."
                    ),
                ),
                (
                    "attempt",
                    models.PositiveIntegerField(default=0, editable=False, help_text="Number of execution attempts."),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        editable=False, help_text="Date and time when the current execution attempt started.", null=True
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        editable=False,
                        help_text="Date and time when the current execution attempt finished.",
                        null=True,
                    ),
                ),
                (
                    "flagged_individuals",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Individuals flagged by this operation.",
                        related_name="flagged_by_rdp_operations",
                        to="country_workspace.individual",
                    ),
                ),
                (
                    "rdp",
                    models.ForeignKey(
                        help_text="RDP this operation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="country_workspace.rdp",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rdp", "operation_type"),
                        name="uniq_rdp_operation_type",
                        violation_error_message="An operation of this type already exists for this RDP.",
                    )
                ],
            },
        ),
    ]
