# Generated by Django 5.2.14 on 2026-09-24 09:02

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0065_rdpoperation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rdpoperation",
            name="flagged_individuals",
        ),
        migrations.CreateModel(
            name="RdpOperationFinding",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                ("finding_type", models.CharField(help_text="Operation-specific finding type.", max_length=50)),
                (
                    "field_name",
                    models.CharField(
                        blank=True, help_text="Field affected by this finding, when applicable.", max_length=255
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, help_text="Operation-specific finding details."),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        help_text="Individual affected by this finding.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdp_operation_findings",
                        to="country_workspace.individual",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        help_text="Operation that produced this finding.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="country_workspace.rdpoperation",
                    ),
                ),
                (
                    "related_individual",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related individual for findings involving another record.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="country_workspace.individual",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
