# Generated by Django 5.2.14 on 2026-09-10 06:30

import concurrency.fields
import country_workspace.models.rdp_operation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0065_ocr_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="rdp_operations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Workspace-managed RDP operations. Operations managed by HOPE are not stored here.",
            ),
        ),
        migrations.CreateModel(
            name="RdpOperation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                (
                    "type",
                    models.CharField(
                        choices=country_workspace.models.rdp_operation.get_rdp_operation_type_choices,
                        help_text="Type of operation to perform for this RDP.",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=country_workspace.models.rdp_operation.get_rdp_operation_status_choices,
                        default="PENDING",
                        help_text="Current execution status of the operation.",
                        max_length=16,
                    ),
                ),
                (
                    "attempt_id",
                    models.UUIDField(
                        editable=False,
                        help_text="Unique identifier of the current or most recent execution attempt.",
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of the corresponding object in the external service, when applicable.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "operation_log",
                    models.JSONField(
                        blank=True, default=list, help_text="Append-only chronological log of this operation."
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the current or most recent execution attempt started.",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the current or most recent execution attempt completed.",
                        null=True,
                    ),
                ),
                (
                    "rdp",
                    models.ForeignKey(
                        help_text="RDP this operation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="country_workspace.rdp",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("rdp", "type"), name="uniq_rdp_operation_type")],
            },
        ),
    ]
