# Generated by Django 5.2.14 on 2026-09-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0066_remove_rdpoperation_flagged_individuals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rdpoperationfinding",
            name="related_individual",
            field=models.ForeignKey(
                blank=True,
                help_text="Related individual for findings involving another record.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_rdp_operation_findings",
                to="country_workspace.individual",
            ),
        ),
    ]
