# Generated by Django 5.2.14 on 2026-09-27 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0067_alter_rdpoperationfinding_related_individual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rdp",
            options={
                "permissions": [
                    ("cancel_rdp", "Can cancel RDP"),
                    ("create_rdp", "Can create RDP from selected beneficiaries"),
                    ("push_rdp_to_hope", "Can push RDP to HOPE"),
                    ("reset_rdp", "Can reset RDP"),
                ],
                "verbose_name": "Registration Data Push",
                "verbose_name_plural": "Registration Data Pushes",
            },
        ),
    ]
