# Generated by Django 5.2.14 on 2026-09-28 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0068_alter_rdp_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rdp",
            name="deduplication_findings_count",
        ),
        migrations.RemoveField(
            model_name="rdp",
            name="deduplication_set_id",
        ),
        migrations.RemoveField(
            model_name="rdp",
            name="duplicate_individuals",
        ),
        migrations.RemoveField(
            model_name="rdp",
            name="is_dedup_settings_locked",
        ),
    ]
