# Generated by Django 5.1.1 on 2024-10-09 06:19
from hope_flex_fields.models import DataChecker, FieldDefinition, Fieldset

from country_workspace.constants import HOUSEHOLD_CHECKER_NAME, INDIVIDUAL_CHECKER_NAME
from country_workspace.versioning.checkers import create_hope_core_fieldset, create_hope_field_definitions


def removes_hope_field_definitions():
    FieldDefinition.objects.filter(name__startswith="HOPE ").delete()


def removes_hope_core_fieldset():
    Fieldset.objects.filter(name=INDIVIDUAL_CHECKER_NAME).delete()
    DataChecker.objects.filter(name=INDIVIDUAL_CHECKER_NAME).delete()

    Fieldset.objects.filter(name=HOUSEHOLD_CHECKER_NAME).delete()
    DataChecker.objects.filter(name=HOUSEHOLD_CHECKER_NAME).delete()


class Scripts:
    operations = [
        (create_hope_field_definitions, removes_hope_field_definitions),
        (create_hope_core_fieldset, removes_hope_core_fieldset),
    ]
