# Generated by HCW 0.1.0 on 2024 10 22 00:15:31
from packaging.version import Version

from country_workspace.versioning.checkers import create_hope_checkers, removes_hope_checkers

_script_for_version = Version("0.1.0")


def forward() -> None:
    pass


def backward() -> None:
    pass


class Scripts:
    operations = [
        (create_hope_checkers, removes_hope_checkers),
    ]
