# Generated by HCW 0.1.0 on 2025 04 15 09:25:45
from concurrency.utils import fqn
from hope_flex_fields.models import FieldDefinition
from hope_flex_fields.registry import field_registry
from hope_flex_fields.utils import get_kwargs_from_field_class, get_common_attrs
from packaging.version import Version

from country_workspace.utils.flex_fields import Base64ImageField

_script_for_version = Version("0.1.0")


def forward() -> None:
    field_registry.register(Base64ImageField)
    FieldDefinition.objects.get_or_create(
        name=Base64ImageField.__name__,
        field_type=fqn(Base64ImageField),
        defaults={"attrs": get_kwargs_from_field_class(Base64ImageField, get_common_attrs())},
    )


def backward() -> None:
    FieldDefinition.objects.filter(
        name=Base64ImageField.__name__,
        field_type=fqn(Base64ImageField),
    ).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
