# Generated by HCW 0.1.0 on 2025 06 23 11:12:31
from concurrency.utils import fqn
from django.db import transaction
from hope_flex_fields.models import Fieldset, DataChecker, DataCheckerFieldset, FieldDefinition
from hope_flex_fields.registry import field_registry
from hope_flex_fields.utils import get_kwargs_from_field_class, get_common_attrs
from packaging.version import Version

from django import forms

from country_workspace.contrib.hope.constants import (
    INDIVIDUAL_CHECKER_NAME,
    DOCUMENT_FIELDSET_NAME,
    ACCOUNT_FIELDSET_NAME,
)
from country_workspace.contrib.hope.lookups import FinancialInstitutionChoice
from country_workspace.utils.flex_fields import Base64ImageField

_script_for_version = Version("0.1.0")


fields_to_remove = [
    ("national_id_issuer", {"field_type": forms.CharField}, {}),
    ("national_id_no", {"field_type": forms.CharField}, {}),
    ("national_id_photo", {"field_type": forms.CharField}, {}),
    ("phone_no", {"field_type": forms.CharField}, {}),
]

document_fields = [
    ("document_number", {"field_type": forms.CharField}, {}),
    ("photo", {"field_type": Base64ImageField}, {}),
    ("issuance_date", {"field_type": forms.DateField}, {}),
    ("expiry_date", {"field_type": forms.DateField}, {}),
    ("country", {"name": "CountryChoice"}, {}),
]

account_fields = [
    ("number", {"field_type": forms.CharField}, {}),
    ("data", {"field_type": forms.JSONField}, {}),
    ("unique_key", {"field_type": forms.CharField}, {}),
    ("financial_institution", {"name": "FinancialInstitutionChoice"}, {}),
]


def remove_document_and_account_fields_from_individual_fieldset() -> None:
    fieldset = Fieldset.objects.get(name=INDIVIDUAL_CHECKER_NAME)
    for field_name, _, _ in fields_to_remove:
        fieldset.fields.get(name=field_name).delete()


def add_document_and_account_fields_to_individual_fieldset() -> None:
    individual_fieldset, _ = Fieldset.objects.get_or_create(name=INDIVIDUAL_CHECKER_NAME)
    for field_name, field_def, field_attrs in fields_to_remove:
        individual_fieldset.fields.get_or_create(
            name=field_name,
            definition=FieldDefinition.objects.get(**field_def),
            defaults={"attrs": field_attrs or {}},
        )


def add_financial_institution_field_definitions() -> None:
    field_registry.register(FinancialInstitutionChoice)
    FieldDefinition.objects.get_or_create(
        name=FinancialInstitutionChoice.__name__,
        field_type=fqn(FinancialInstitutionChoice),
        defaults={"attrs": get_kwargs_from_field_class(FinancialInstitutionChoice, get_common_attrs())},
    )


def remove_financial_institution_field_definitions() -> None:
    FieldDefinition.objects.filter(
        name=FinancialInstitutionChoice.__name__,
        field_type=fqn(FinancialInstitutionChoice),
    ).delete()


def add_fields_to_fieldsets(fieldset: Fieldset, fields: list) -> None:
    for field_name, field_def, field_attrs in fields:
        fieldset.fields.get_or_create(
            name=field_name, definition=FieldDefinition.objects.get(**field_def), defaults={"attrs": field_attrs or {}}
        )


def add_account_and_document_fieldsets() -> None:
    ind_datachecker = DataChecker.objects.get(name=INDIVIDUAL_CHECKER_NAME)

    document_fieldset, _ = Fieldset.objects.get_or_create(name=DOCUMENT_FIELDSET_NAME)
    account_fieldset, _ = Fieldset.objects.get_or_create(name=ACCOUNT_FIELDSET_NAME)
    for fieldset, prefixes in (
        (document_fieldset, ("national_id__", "national_passport__")),
        (account_fieldset, ("phone__", "bank__")),
    ):
        for prefix in prefixes:
            DataCheckerFieldset.objects.get_or_create(checker=ind_datachecker, fieldset=fieldset, prefix=prefix)

    for fieldset, fields in ((document_fieldset, document_fields), (account_fieldset, account_fields)):
        add_fields_to_fieldsets(fieldset, fields)


def remove_account_and_document_fieldsets() -> None:
    Fieldset.objects.filter(name__in=[DOCUMENT_FIELDSET_NAME, ACCOUNT_FIELDSET_NAME]).delete()


def forward() -> None:
    with transaction.atomic():
        remove_document_and_account_fields_from_individual_fieldset()

        add_financial_institution_field_definitions()

        add_account_and_document_fieldsets()


def backward() -> None:
    with transaction.atomic():
        remove_account_and_document_fieldsets()

        remove_financial_institution_field_definitions()

        add_document_and_account_fields_to_individual_fieldset()


class Scripts:
    requires = []
    operations = [(forward, backward)]
