# Generated by HCW 0.1.0 on 2025 07 01 09:07:25
from collections.abc import Callable
from typing import Final
from contextlib import suppress
from django.db import transaction
from hope_flex_fields.models import Fieldset, DataChecker
from packaging.version import Version


from country_workspace.contrib.hope.constants import (
    HOUSEHOLD_CHECKER_NAME,
    PEOPLE_CHECKER_NAME,
    ADMINAREAS_FIELDSET_NAME,
    HOUSEHOLD_FIELDSET_NAME,
)


_script_for_version = Version("0.1.0")


FIELDSETS: Final[dict] = {
    "admin_areas": {
        "name": ADMINAREAS_FIELDSET_NAME,
        "defaults": {"description": "Administrative areas fields"},
    },
    "HH_core": {
        "name": HOUSEHOLD_FIELDSET_NAME,
        "defaults": {"description": "Household core fields"},
    },
}

FIELDS = ("admin1", "admin2", "admin3", "admin4")


def setup_fieldsets() -> tuple[Fieldset, Fieldset, Callable]:
    fs_aa, __ = Fieldset.objects.get_or_create(**FIELDSETS["admin_areas"])
    fs_hh, __ = Fieldset.objects.get_or_create(**FIELDSETS["HH_core"])

    def toggle_admin_fieldset(*, add: bool = True) -> None:
        action = "add" if add else "remove"
        for checker_name in (HOUSEHOLD_CHECKER_NAME, PEOPLE_CHECKER_NAME):
            with suppress(DataChecker.DoesNotExist):
                checker = DataChecker.objects.get(name=checker_name)
                getattr(checker.fieldsets, action)(fs_aa)

    return fs_aa, fs_hh, toggle_admin_fieldset


def move_fields(from_fs: Fieldset, to_fs: Fieldset) -> None:
    from_fs.fields.filter(name__in=FIELDS).update(fieldset=to_fs)


def forward() -> None:
    with transaction.atomic():
        fs_aa, fs_hh, toggle_admin = setup_fieldsets()
        move_fields(fs_hh, fs_aa)
        toggle_admin(add=True)


def backward() -> None:
    with transaction.atomic():
        fs_aa, fs_hh, toggle_admin = setup_fieldsets()
        move_fields(fs_aa, fs_hh)
        toggle_admin(add=False)
        fs_aa.delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
