# Generated by HCW 0.1.0 on 2025 07 14 18:14:41
from django import forms
from hope_flex_fields.models import Fieldset, FieldDefinition
from packaging.version import Version

from country_workspace.contrib.hope.constants import HOUSEHOLD_FIELDSET_NAME

_script_for_version = Version("0.1.0")


field_to_remove = "collect_individual_data"
household_fieldset = Fieldset.objects.get(name=HOUSEHOLD_FIELDSET_NAME)


def forward() -> None:
    household_fieldset.fields.filter(name=field_to_remove).delete()


def backward() -> None:
    household_fieldset.fields.get_or_create(
        name=field_to_remove,
        definition=FieldDefinition.objects.get(field_type=forms.BooleanField),
        defaults={"attrs": {}},
    )


class Scripts:
    requires = []
    operations = [(forward, backward)]
