# Generated by HCW 0.1.0 on 2025 07 09 08:26:20
from packaging.version import Version
from contextlib import suppress
from concurrency.utils import fqn

from django import forms
from django.db import transaction
from django.utils.text import slugify

from hope_flex_fields.models import FieldDefinition, FlexField, Fieldset
from hope_flex_fields.utils import get_kwargs_from_field_class, get_common_attrs

from country_workspace.contrib.hope.constants import HOUSEHOLD_FIELDSET_NAME


_script_for_version = Version("0.1.0")


attrs_default = lambda cls: get_kwargs_from_field_class(cls, get_common_attrs())


FIELDS = {
    "org_enumerator": {
        "forward": {
            "name": "HOPE org enumerator",
            "defaults": {
                "field_type": fqn(forms.ChoiceField),
                "attrs": {
                    **attrs_default(forms.ChoiceField),
                    "choices": [
                        ["", "None"],
                        ["PARTNER", "Partner"],
                        ["UNICEF", "UNICEF"],
                    ],
                },
            },
        },
        "backward": {
            "name": "CharField",
        },
    },
    "registration_method": {
        "forward": {
            "name": "HOPE registration method",
            "defaults": {
                "field_type": fqn(forms.ChoiceField),
                "attrs": {
                    **attrs_default(forms.ChoiceField),
                    "choices": [
                        ["", "None"],
                        ["COMMUNITY", "Community-level Registration"],
                        ["HH_REGISTRATION", "Household Registration"],
                    ],
                },
            },
        },
        "backward": {
            "name": "CharField",
        },
    },
}


def forward() -> None:
    with transaction.atomic():
        fs, __ = Fieldset.objects.get_or_create(name=HOUSEHOLD_FIELDSET_NAME)
        for field_name, field_def in FIELDS.items():
            field_def["forward"]["defaults"]["slug"] = slugify(field_def["forward"]["name"])
            fd, __ = FieldDefinition.objects.update_or_create(**field_def["forward"])
            FlexField.objects.update_or_create(
                name=field_name,
                fieldset=fs,
                defaults={
                    "definition": fd,
                },
            )


def backward() -> None:
    with transaction.atomic():
        for field_name, field_def in FIELDS.items():
            fd = FieldDefinition.objects.get(name=field_def["backward"]["name"])
            FlexField.objects.filter(name=field_name, fieldset__name=HOUSEHOLD_FIELDSET_NAME).update(definition=fd)
            with suppress(FieldDefinition.DoesNotExist):
                FieldDefinition.objects.get(name=field_def["forward"]["name"]).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
