# Generated by HCW 0.1.0 on 2025 07 21 09:24:32
from concurrency.utils import fqn
from django import forms
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.models import Fieldset, FieldDefinition
from packaging.version import Version

from country_workspace.contrib.hope.constants import INDIVIDUAL_FIELDSET_NAME


_script_for_version = Version("0.1.0")


FIELDS = {
    "phone_no": {"name": "PhoneNo", "defaults": {"field_type": fqn(forms.CharField)}},
    "phone_no_alternative": {"name": "PhoneNoAlternative", "defaults": {"field_type": fqn(forms.CharField)}},
}


def forward() -> None:
    with transaction.atomic():
        fs, __ = Fieldset.objects.get_or_create(name=INDIVIDUAL_FIELDSET_NAME)
        for field_name, field_def in FIELDS.items():
            field_def["defaults"]["slug"] = slugify(field_def["name"])
            fd, __ = FieldDefinition.objects.get_or_create(**field_def)
            fs.fields.update_or_create(
                name=field_name,
                defaults={
                    "definition": fd,
                },
            )


def backward() -> None:
    with transaction.atomic():
        try:
            fs = Fieldset.objects.get(name=INDIVIDUAL_FIELDSET_NAME)
        except Fieldset.DoesNotExist:
            return

        for field_name, field_def in FIELDS.items():
            fs.fields.filter(name=field_name).delete()
            FieldDefinition.objects.filter(name=field_def["name"]).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
