# Generated by HCW 0.1.0 on 2025 07 29 07:39:07
from typing import Any
from packaging.version import Version
from concurrency.utils import fqn
from contextlib import suppress
from django import forms
from django.db import transaction
from django.utils.text import slugify

from hope_flex_fields.models import FieldDefinition, Fieldset
from hope_flex_fields.utils import get_kwargs_from_field_class, get_common_attrs
from country_workspace.contrib.hope.beneficiary_reference import BeneficiaryReferenceModelChoiceField
from country_workspace.contrib.hope.constants import HOUSEHOLD_FIELDSET_NAME, INDIVIDUAL_FIELDSET_NAME

_script_for_version = Version("0.1.0")


attrs_default = lambda cls: get_kwargs_from_field_class(cls, get_common_attrs())

FIELDS: dict[str, dict[str, Any]] = {
    "alternate_collector_id": {
        "name": "Alternate Collector Reference ID",
        "defaults": {
            "field_type": fqn(BeneficiaryReferenceModelChoiceField),
            "attrs": {
                **attrs_default(BeneficiaryReferenceModelChoiceField),
                "help_text": "A unique beneficiary reference ID for an alternate collector.",
            },
        },
    },
    "primary_collector_id": {
        "name": "Primary Collector Reference ID",
        "defaults": {
            "field_type": fqn(BeneficiaryReferenceModelChoiceField),
            "attrs": {
                **attrs_default(BeneficiaryReferenceModelChoiceField),
                "help_text": "A unique beneficiary reference ID for a primary collector.",
            },
        },
    },
    "individual_id": {
        "name": "Individual ID",
        "defaults": {
            "field_type": fqn(forms.CharField),
            "attrs": {
                **attrs_default(forms.CharField),
                "help_text": "A unique individual ID.",
            },
        },
    },
}


FIELDSETS = {
    HOUSEHOLD_FIELDSET_NAME: ("alternate_collector_id", "primary_collector_id"),
    INDIVIDUAL_FIELDSET_NAME: ("individual_id",),
}


def forward() -> None:
    with transaction.atomic():
        for fieldset_name, field_names in FIELDSETS.items():
            fs, __ = Fieldset.objects.get_or_create(name=fieldset_name)
            for field_name in field_names:
                field_def = FIELDS[field_name]
                field_def["defaults"]["slug"] = slugify(field_def["name"])
                fd, __ = FieldDefinition.objects.update_or_create(
                    name=field_def["name"], defaults=field_def["defaults"]
                )
                fs.fields.update_or_create(name=field_name, defaults={"definition": fd})


def backward() -> None:
    with transaction.atomic():
        for fieldset_name, field_names in FIELDSETS.items():
            try:
                fs = Fieldset.objects.get(name=fieldset_name)
            except Fieldset.DoesNotExist:
                continue

            for field_name in field_names:
                fs.fields.filter(name=field_name).delete()
                with suppress(FieldDefinition.DoesNotExist):
                    fd = FieldDefinition.objects.get(name=FIELDS[field_name]["name"])
                    fd.delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
