# Generated by HCW 0.1.0 on 2025 08 14 09:59:08
from typing import Any
from packaging.version import Version
from concurrency.utils import fqn
from contextlib import suppress
from django.db import transaction

from hope_flex_fields.models import FieldDefinition, Fieldset
from hope_flex_fields.utils import get_kwargs_from_field_class, get_common_attrs
from country_workspace.contrib.hope.beneficiary_reference import BeneficiaryReferenceModelChoiceField
from country_workspace.contrib.hope.constants import HOUSEHOLD_FIELDSET_NAME, INDIVIDUAL_FIELDSET_NAME

_script_for_version = Version("0.1.0")

attrs_default = lambda cls: get_kwargs_from_field_class(cls, get_common_attrs())

FIELDS: dict[str, dict[str, Any]] = {
    "head_of_household_id": {
        "name": "Head of Household ID",
        "defaults": {
            "field_type": fqn(BeneficiaryReferenceModelChoiceField),
            "attrs": {
                **attrs_default(BeneficiaryReferenceModelChoiceField),
                "limit_to_household": True,
                "help_text": "A unique beneficiary reference ID for the head of household.",
            },
        },
    },
    "primary_collector_id": {"name": "CharField"},
    "alternate_collector_id": {"name": "CharField"},
}

PLAN = {
    HOUSEHOLD_FIELDSET_NAME: ("add", ("head_of_household_id",)),
    INDIVIDUAL_FIELDSET_NAME: ("delete", ("primary_collector_id", "alternate_collector_id")),
}


def _fd(key: str) -> FieldDefinition:
    spec = FIELDS[key]
    if "defaults" in spec:
        fd, _ = FieldDefinition.objects.update_or_create(name=spec["name"], defaults=spec["defaults"])
        return fd
    return FieldDefinition.objects.get(name=spec["name"])


def _apply(invert: bool = False) -> None:
    for fs_name, (op, keys) in PLAN.items():
        action = op if not invert else ("delete" if op == "add" else "add")
        fs, _ = Fieldset.objects.get_or_create(name=fs_name)
        if action == "delete":
            fs.fields.filter(name__in=keys).delete()
        else:
            for k in keys:
                with suppress(FieldDefinition.DoesNotExist):
                    fs.fields.update_or_create(name=k, defaults={"definition": _fd(k)})


@transaction.atomic
def forward() -> None:
    _apply()


@transaction.atomic
def backward() -> None:
    _apply(invert=True)


class Scripts:
    requires = []
    operations = [(forward, backward)]
