# Generated by HCW 0.1.0 on 2025 08 21 09:07:06
from packaging.version import Version
from django.db import transaction
from hope_flex_fields.models import Fieldset, DataChecker, DataCheckerFieldset
from country_workspace.contrib.hope.constants import INDIVIDUAL_CHECKER_NAME, DOCUMENT_TYPES, ACCOUNT_TYPES

_script_for_version = Version("0.1.0")


DEF_TYPES = {
    "HOPE Document": {
        "defaults": {"group": "documents", "description": "Identity documents."},
        "types_old": DOCUMENT_TYPES,
        "types": ("birth_certificate",),
    },
    "HOPE Account": {
        "defaults": {"group": "accounts", "description": "Financial accounts and payout methods."},
        "types_old": ACCOUNT_TYPES,
        "types": ("cash",),
    },
}

DEF_FIELDNAME = {"HOPE Document": {"old_name": "photo", "new_name": "image"}}


def _rename_fields(forward: bool) -> None:
    for fs_name, names in DEF_FIELDNAME.items():
        old_name, new_name = (
            (names["old_name"], names["new_name"]) if forward else (names["new_name"], names["old_name"])
        )
        for fs in Fieldset.objects.filter(name=fs_name).only("id"):
            fs.fields.filter(name=old_name).update(name=new_name)


@transaction.atomic
def forward() -> None:
    _rename_fields(forward=True)

    checker = DataChecker.objects.filter(name=INDIVIDUAL_CHECKER_NAME).only("id").first()
    if not checker:
        return

    for fs_name, info in DEF_TYPES.items():
        fs, _ = Fieldset.objects.update_or_create(name=fs_name, defaults=info["defaults"])
        for t in info["types"] + info["types_old"]:
            DataCheckerFieldset.objects.update_or_create(checker=checker, fieldset=fs, prefix=f"{t}_")


@transaction.atomic
def backward() -> None:
    _rename_fields(forward=False)

    checker = DataChecker.objects.filter(name=INDIVIDUAL_CHECKER_NAME).only("id").first()
    if not checker:
        return

    DataCheckerFieldset.objects.filter(
        checker=checker,
        fieldset__name__in=DEF_TYPES.keys(),
        prefix__in=[f"{t}_" for v in DEF_TYPES.values() for t in v["types"]],
    ).delete()

    for name, info in DEF_TYPES.items():
        d = info["defaults"]
        Fieldset.objects.filter(name=name, group=d["group"], description=d["description"]).update(
            group=None, description=""
        )


class Scripts:
    requires = []
    operations = [(forward, backward)]
