# Generated by HCW 0.1.0 on 2025 08 27 08:01:55
from packaging.version import Version
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.models import FlexField

_script_for_version = Version("0.1.0")

FWD = {
    "alternate_collector_id": "alternate_collector",
    "primary_collector_id": "primary_collector",
    "head_of_household_id": "head_of_household",
}
bwd = {v: k for k, v in FWD.items()}


def _apply(name_map: dict[str, str]) -> None:
    qs = FlexField.objects.filter(name__in=name_map).select_related("fieldset")
    for f in qs:
        new = name_map[f.name]
        if f.name == new:
            continue
        if FlexField.objects.filter(fieldset=f.fieldset, name=new).exclude(pk=f.pk).exists():
            continue

        f.name = new
        f.slug = slugify(new)
        f.save(update_fields=["name", "slug"])


@transaction.atomic
def forward() -> None:
    _apply(FWD)


@transaction.atomic
def backward() -> None:
    _apply(bwd)


class Scripts:
    requires = []
    operations = [(forward, backward)]
