# Generated by HCW 0.1.0 on 2025 08 27 08:15:36
from packaging.version import Version
from django.db import transaction
from country_workspace.models import DataSerializer

_script_for_version = Version("0.1.0")

NAME = "remove_nullable"
CODE = """function serialize(data) {
  function isArray(x) {
    return Object.prototype.toString.call(x) === "[object Array]";
  }
  function clean(v) {
    if (isArray(v)) {
      var out = [];
      for (var i = 0; i < v.length; i++) out.push(clean(v[i]));
      return out;
    }
    if (v && typeof v === "object") {
      var obj = {};
      for (var k in v) if (Object.prototype.hasOwnProperty.call(v, k)) {
        var val = v[k];
        if (val !== null) obj[k] = clean(val);
      }
      return obj;
    }
    return v;
  }
  return clean(data);
}"""


@transaction.atomic
def forward() -> None:
    obj, created = DataSerializer.objects.get_or_create(name=NAME, defaults={"code": CODE})
    if not created and obj.code != CODE:
        obj.code = CODE
        obj.full_clean()
        obj.save(update_fields=["code"])


@transaction.atomic
def backward() -> None:
    DataSerializer.objects.filter(name=NAME, code=CODE).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
