# Generated by HCW 0.1.0 on 2025 08 29 12:02:51
from concurrency.utils import fqn
from django import forms
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.models import Fieldset, FieldDefinition
from packaging.version import Version

from country_workspace.contrib.hope.constants import INDIVIDUAL_FIELDSET_NAME, PEOPLE_FIELDSET_NAME

_script_for_version = Version("0.1.0")

FIELDS_INFO = [
    {
        "fields": {
            "household_id": {"name": "Household ID", "defaults": {"field_type": fqn(forms.IntegerField)}},
        },
        "fieldset_name": INDIVIDUAL_FIELDSET_NAME,
    },
    {
        "fields": {
            "index_id": {"name": "Household ID", "defaults": {"field_type": fqn(forms.IntegerField)}},
        },
        "fieldset_name": PEOPLE_FIELDSET_NAME,
    },
]


def forward() -> None:
    with transaction.atomic():
        for field_info in FIELDS_INFO:
            fs, __ = Fieldset.objects.get_or_create(name=field_info["fieldset_name"])
            for field_name, field_def in field_info["fields"].items():
                field_def["defaults"]["slug"] = slugify(field_def["name"])
                fd, __ = FieldDefinition.objects.get_or_create(**field_def)
                fs.fields.update_or_create(
                    name=field_name,
                    defaults={
                        "definition": fd,
                    },
                )


def backward() -> None:
    with transaction.atomic():
        for field_info in FIELDS_INFO:
            fs = Fieldset.objects.filter(name=field_info["fieldset_name"]).first()
            if not fs:
                return

            for field_name, field_def in field_info["fields"].items():
                fs.fields.filter(name=field_name).delete()
                FieldDefinition.objects.filter(name=field_def["name"]).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
