# Generated by HCW 0.1.0 on 2025 09 16 07:31:39
from typing import Final
from packaging.version import Version
from django.db import transaction
from hope_flex_fields.models import FieldDefinition


_script_for_version = Version("0.1.0")


NAME: Final[str] = "HOPE People Type"

CHOICES: Final[dict[str, list[list[str]]]] = {
    "forward": [
        ["", "None"],
        ["NON_BENEFICIARY", "Non Beneficiary"],
    ],
    "backward": [
        ["", ""],
        ["NON_BENEFICIARY", "Non Beneficiary"],
    ],
}


def _apply(choices: list[list[str]]) -> None:
    FieldDefinition.objects.update_or_create(
        name=NAME,
        defaults={"attrs": {"choices": choices}},
    )


@transaction.atomic()
def forward() -> None:
    _apply(CHOICES["forward"])


@transaction.atomic()
def backward() -> None:
    _apply(CHOICES["backward"])


class Scripts:
    requires = []
    operations = [(forward, backward)]
