# Generated by HCW 0.1.0 on 2025 09 12 11:06:58
from packaging.version import Version
from collections.abc import Iterable, Mapping
from django.db import transaction

from hope_flex_fields.models import Fieldset, DataChecker, DataCheckerFieldset
from country_workspace.contrib.hope.constants import (
    INDIVIDUAL_CHECKER_NAME,
    PEOPLE_CHECKER_NAME,
    DOCUMENT_FIELDSET_NAME,
    ACCOUNT_FIELDSET_NAME,
)

_script_for_version = Version("0.1.0")


DEFS: Mapping[str, Mapping[str, Iterable[str]]] = {
    INDIVIDUAL_CHECKER_NAME: {
        DOCUMENT_FIELDSET_NAME: ("electoral_card_",),
    },
    PEOPLE_CHECKER_NAME: {
        DOCUMENT_FIELDSET_NAME: ("national_id_", "national_passport_"),
        ACCOUNT_FIELDSET_NAME: ("bank_", "electoral_card_"),
    },
}


def get_by_name(model: type[Fieldset | DataChecker], name: str) -> Fieldset | DataChecker:
    return model.objects.only("id").get(name=name)


@transaction.atomic
def forward() -> None:
    for cname, fmap in DEFS.items():
        dc = get_by_name(DataChecker, cname)
        for fname, prefixes in fmap.items():
            fs = get_by_name(Fieldset, fname)
            for p in prefixes:
                DataCheckerFieldset.objects.update_or_create(checker=dc, fieldset=fs, prefix=p)


@transaction.atomic
def backward() -> None:
    for cname, fmap in DEFS.items():
        for fname, prefixes in fmap.items():
            DataCheckerFieldset.objects.filter(checker__name=cname, fieldset__name=fname, prefix__in=prefixes).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
