# Generated by HCW 0.1.0 on 2025 09 24 07:57:40
from typing import Final, Mapping
from packaging.version import Version
from django.db import transaction
from hope_flex_fields.models import FlexField

_script_for_version = Version("0.1.0")

type Attrs = Mapping[str, str | bool]

FIELD_NAME: Final[str] = "consent"
FORWARD_ATTRS: Final[Attrs] = {"label": "Consent", "required": False}
BACKWARD_ATTRS: Final[Attrs] = {}


def _apply(attrs: Attrs) -> None:
    FlexField.objects.update_or_create(name=FIELD_NAME, defaults={"attrs": attrs})


@transaction.atomic()
def forward() -> None:
    _apply(FORWARD_ATTRS)


@transaction.atomic()
def backward() -> None:
    _apply(BACKWARD_ATTRS)


class Scripts:
    requires = []
    operations = [(forward, backward)]
