# Generated by HCW 0.1.0 on 2025 09 16 18:51:09
from django import forms
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.models import Fieldset, FieldDefinition
from hope_flex_fields.registry import field_registry
from packaging.version import Version
from concurrency.utils import fqn

from country_workspace.contrib.hope.constants import HOUSEHOLD_FIELDSET_NAME
from country_workspace.utils.flex_fields import Base64ImageField
from country_workspace.versioning.choices.currency import CURRENCY_CHOICES

_script_for_version = Version("0.1.0")

DEFS = {
    "CharField": {"field_type": forms.CharField},
    "PositiveIntegerField": {"field_type": forms.IntegerField, "attrs": {"min_value": 0}},
    "BooleanField": {"field_type": forms.BooleanField, "attrs": {"required": False}},
}

FIELDS = {
    "consent_sign": {
        "name": "Consent Sign",
        "defaults": {"field_type": fqn(Base64ImageField)},
    },
    "zip_code": {
        "name": "Zip Code",
        "defaults": DEFS["CharField"],
    },
    "children_count": {
        "name": "Children count",
        "defaults": DEFS["PositiveIntegerField"],
    },
    "male_children_count": {
        "name": "Male Children Count",
        "defaults": DEFS["PositiveIntegerField"],
    },
    "female_children_count": {
        "name": "Female Children Count",
        "defaults": DEFS["PositiveIntegerField"],
    },
    "children_disabled_count": {
        "name": "Children Disabled Count",
        "defaults": DEFS["PositiveIntegerField"],
    },
    "male_children_disabled_count": {
        "name": "Male Children Disabled Count",
        "defaults": DEFS["PositiveIntegerField"],
    },
    "female_children_disabled_count": {
        "name": "Female Children disabled Count",
        "defaults": DEFS["PositiveIntegerField"],
    },
    "other_sex_group_count": {
        "name": "Other Sex Group Count",
        "defaults": DEFS["PositiveIntegerField"],
    },
    "unknown_sex_group_count": {
        "name": "Unknown Sex Group Count",
        "defaults": DEFS["PositiveIntegerField"],
    },
    "returnee": {
        "name": "Returnee",
        "defaults": DEFS["BooleanField"],
    },
    "fchild_hoh": {
        "name": "Fchild HOH",
        "defaults": DEFS["BooleanField"],
    },
    "child_hoh": {
        "name": "Child HOH",
        "defaults": DEFS["BooleanField"],
    },
    "village": {
        "name": "Village",
        "defaults": DEFS["CharField"],
    },
    "currency": {
        "name": "Currency",
        "defaults": {
            "field_type": forms.ChoiceField,
            "attrs": {"choices": CURRENCY_CHOICES},
        },
    },
    "unhcr_id": {
        "name": "Unhcr ID",
        "defaults": DEFS["CharField"],
    },
    "detail_id": {
        "name": "Detail ID",
        "defaults": DEFS["CharField"],
    },
    "start": {
        "name": "Start",
        "defaults": {
            "field_type": forms.DateTimeField,
        },
    },
}


def forward() -> None:
    field_registry.register(Base64ImageField)
    with transaction.atomic():
        fs, __ = Fieldset.objects.get_or_create(name=HOUSEHOLD_FIELDSET_NAME)
        for field_name, field_def in FIELDS.items():
            field_def["defaults"]["slug"] = slugify(field_def["name"])
            fd, __ = FieldDefinition.objects.get_or_create(**field_def)
            fs.fields.update_or_create(
                name=field_name,
                defaults={
                    "definition": fd,
                },
            )


def backward() -> None:
    with transaction.atomic():
        fs = Fieldset.objects.filter(name=HOUSEHOLD_FIELDSET_NAME).first()
        if not fs:
            return

        for field_name, field_def in FIELDS.items():
            fs.fields.filter(name=field_name).delete()
            FieldDefinition.objects.filter(name=field_def["name"]).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
