# Generated by HCW 0.1.0 on 2025 09 17 11:34:18
from django import forms
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.models import Fieldset, FieldDefinition
from hope_flex_fields.registry import field_registry
from packaging.version import Version
from concurrency.utils import fqn

from country_workspace.contrib.hope.constants import INDIVIDUAL_FIELDSET_NAME
from country_workspace.utils.flex_fields import Base64ImageField
from country_workspace.contrib.hope.phone_numbers import PhoneNumberField

from country_workspace.versioning.choices.language import PREFERRED_LANGUAGE_CHOICES
from country_workspace.versioning.choices.marital_status import MARITAL_STATUS_CHOICE
from country_workspace.versioning.choices.work_status import WORK_STATUS_CHOICE
from country_workspace.versioning.choices.disability import (
    OBSERVED_DISABILITY_CHOICE,
    SEVERITY_OF_DISABILITY_CHOICES,
)

_script_for_version = Version("0.1.0")

DEFS = {
    "CharField": {"field_type": forms.CharField},
    "BooleanField": {"field_type": forms.BooleanField, "attrs": {"required": False}},
}


FIELDS = {
    "marital_status": {
        "name": "Marital Status",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": MARITAL_STATUS_CHOICE}},
    },
    "work_status": {
        "name": "Work Status",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": WORK_STATUS_CHOICE}},
    },
    "observed_disability": {
        "name": "Observed Disability",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": OBSERVED_DISABILITY_CHOICE}},
    },
    "seeing_disability": {
        "name": "Seeing Disability",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": SEVERITY_OF_DISABILITY_CHOICES}},
    },
    "hearing_disability": {
        "name": "Hearing Disability",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": SEVERITY_OF_DISABILITY_CHOICES}},
    },
    "physical_disability": {
        "name": "Physical Disability",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": SEVERITY_OF_DISABILITY_CHOICES}},
    },
    "memory_disability": {
        "name": "Memory Disability",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": SEVERITY_OF_DISABILITY_CHOICES}},
    },
    "selfcare_disability": {
        "name": "Selfcare Disability",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": SEVERITY_OF_DISABILITY_CHOICES}},
    },
    "comms_disability": {
        "name": "Comms Disability",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": SEVERITY_OF_DISABILITY_CHOICES}},
    },
    "preferred_language": {
        "name": "Preferred Language",
        "defaults": {"field_type": forms.ChoiceField, "attrs": {"choices": PREFERRED_LANGUAGE_CHOICES}},
    },
    "pregnant": {"name": "Pregnant", "defaults": DEFS["BooleanField"]},
    "relationship_confirmed": {"name": "Relationship Confirmed", "defaults": DEFS["BooleanField"]},
    "fchild_hoh": {"name": "Fchild HOH", "defaults": DEFS["BooleanField"]},
    "child_hoh": {"name": "Child HOH", "defaults": DEFS["BooleanField"]},
    "email": {"name": "Email", "defaults": DEFS["CharField"]},
    "payment_delivery_phone_no": {
        "name": "Payment Delivery Phone No",
        "defaults": {"field_type": fqn(PhoneNumberField)},
    },
    "who_answers_phone": {"name": "Who Answers Phone", "defaults": DEFS["CharField"]},
    "who_answers_alt_phone": {"name": "Who Answers Alt Phone", "defaults": DEFS["CharField"]},
    "wallet_name": {"name": "Wallet Name", "defaults": DEFS["CharField"]},
    "blockchain_name": {"name": "Blockchain Name", "defaults": DEFS["CharField"]},
    "wallet_address": {"name": "Wallet Address", "defaults": DEFS["CharField"]},
    "disability_certificate_picture": {
        "name": "Disability Certificate Picture",
        "defaults": {"field_type": fqn(Base64ImageField)},
    },
}


def forward() -> None:
    field_registry.register(Base64ImageField)
    field_registry.register(PhoneNumberField)
    with transaction.atomic():
        fs, __ = Fieldset.objects.get_or_create(name=INDIVIDUAL_FIELDSET_NAME)
        for field_name, field_def in FIELDS.items():
            field_def["defaults"]["slug"] = slugify(field_def["name"])
            fd, __ = FieldDefinition.objects.get_or_create(**field_def)
            fs.fields.update_or_create(
                name=field_name,
                defaults={
                    "definition": fd,
                },
            )


def backward() -> None:
    with transaction.atomic():
        fs = Fieldset.objects.filter(name=INDIVIDUAL_FIELDSET_NAME).first()
        if not fs:
            return

        for field_name, field_def in FIELDS.items():
            fs.fields.filter(name=field_name).delete()
            FieldDefinition.objects.filter(name=field_def["name"]).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
