# Generated by HCW 0.1.0 on 2025 09 17 11:34:18
from django import forms
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.models import Fieldset, DataChecker, DataCheckerFieldset, FieldDefinition
from hope_flex_fields.registry import field_registry
from packaging.version import Version
from concurrency.utils import fqn

from country_workspace.contrib.hope.constants import (
    INDIVIDUAL_FIELDSET_NAME,
    PEOPLE_FIELDSET_NAME,
    INDIVIDUAL_BASE_FIELDSET_NAME,
    INDIVIDUAL_CHECKER_NAME,
    PEOPLE_CHECKER_NAME,
)
from country_workspace.utils.flex_fields import Base64ImageField
from country_workspace.contrib.hope.phone_numbers import PhoneNumberField

from country_workspace.versioning.choices.language import PREFERRED_LANGUAGE_CHOICES
from country_workspace.versioning.choices.work_status import WORK_STATUS_CHOICES
from country_workspace.versioning.choices.disability import (
    SEVERITY_OF_DISABILITY_CHOICES,
    DISABILITY_CHOICES,
    NOT_DISABLED,
)

_script_for_version = Version("0.1.0")


DEFS = {
    "CharField": {"field_type": forms.CharField},
    "BooleanField": {"field_type": fqn(forms.BooleanField), "attrs": {"required": False}},
    "SeverityOfDisabilityChoices": {
        "field_type": fqn(forms.ChoiceField),
        "attrs": {"choices": SEVERITY_OF_DISABILITY_CHOICES},
    },
    "WorkStatusChoices": {"field_type": fqn(forms.ChoiceField), "attrs": {"choices": WORK_STATUS_CHOICES}},
    "PreferredLanguageChoices": {
        "field_type": fqn(forms.ChoiceField),
        "attrs": {"choices": PREFERRED_LANGUAGE_CHOICES, "required": False},
    },
    "DisabilityChoices": {
        "field_type": fqn(forms.ChoiceField),
        "attrs": {"choices": DISABILITY_CHOICES, "initial": NOT_DISABLED},
    },
}

FIELDS = {
    "observed_disability": {
        "name": "HOPE IND ObservedDisability",
        "definition": {"field_type": fqn(forms.ChoiceField)},
        "attrs": {"label": "Observed Disability"},
    },
    "marital_status": {
        "name": "HOPE IND MaritalStatus",
        "definition": {"field_type": fqn(forms.ChoiceField)},
        "attrs": {"label": "Marital Status"},
    },
    "sex": {
        "name": "HOPE IND Sex",
        "definition": {"field_type": fqn(forms.ChoiceField)},
        "attrs": {"label": "Sex"},
    },
    "disability": {
        "name": "Disability",
        "definition": DEFS["DisabilityChoices"],
        "attrs": {"label": "Disability"},
    },
    "work_status": {
        "name": "Work Status",
        "definition": DEFS["WorkStatusChoices"],
        "attrs": {"label": "Work Status"},
    },
    "seeing_disability": {
        "name": "Seeing Disability",
        "definition": DEFS["SeverityOfDisabilityChoices"],
        "attrs": {"label": "Seeing Disability"},
    },
    "hearing_disability": {
        "name": "Hearing Disability",
        "definition": DEFS["SeverityOfDisabilityChoices"],
        "attrs": {"label": "Hearing Disability"},
    },
    "physical_disability": {
        "name": "Physical Disability",
        "definition": DEFS["SeverityOfDisabilityChoices"],
        "attrs": {"label": "Physical Disability"},
    },
    "memory_disability": {
        "name": "Memory Disability",
        "definition": DEFS["SeverityOfDisabilityChoices"],
        "attrs": {"label": "Memory Disability"},
    },
    "selfcare_disability": {
        "name": "Selfcare Disability",
        "definition": DEFS["SeverityOfDisabilityChoices"],
        "attrs": {"label": "Selfcare Disability"},
    },
    "comms_disability": {
        "name": "Comms Disability",
        "definition": DEFS["SeverityOfDisabilityChoices"],
        "attrs": {"label": "Comms Disability"},
    },
    "preferred_language": {
        "name": "Preferred Language",
        "definition": DEFS["PreferredLanguageChoices"],
        "attrs": {"label": "Preferred Language"},
    },
    "pregnant": {"name": "Pregnant", "definition": DEFS["BooleanField"], "attrs": {"label": "Pregnant"}},
    "relationship_confirmed": {
        "name": "Relationship Confirmed",
        "definition": DEFS["BooleanField"],
        "attrs": {"label": "Relationship Confirmed"},
    },
    "fchild_hoh": {"name": "Fchild HOH", "definition": DEFS["BooleanField"], "attrs": {"label": "Fchild HOH"}},
    "child_hoh": {"name": "Child HOH", "definition": DEFS["BooleanField"], "attrs": {"label": "Child HOH"}},
    "estimated_birth_date": {
        "name": "Estimated Birth Date",
        "definition": DEFS["BooleanField"],
        "attrs": {"label": "Estimated Birth Date"},
    },
    "birth_date": {
        "name": "Birth Date",
        "definition": {"field_type": fqn(forms.DateField)},
        "attrs": {"label": "Birth Date", "required": True},
    },
    "email": {"name": "Email", "definition": DEFS["CharField"], "attrs": {"label": "Email"}},
    "payment_delivery_phone_no": {
        "name": "Payment Delivery Phone No",
        "definition": {"field_type": fqn(PhoneNumberField)},
        "attrs": {"label": "Payment Delivery Phone No"},
    },
    "phone_no": {"name": "Phone No", "definition": DEFS["CharField"], "attrs": {"label": "Phone No"}},
    "phone_no_alternative": {
        "name": "Phone No Alternative",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Phone No Alternative"},
    },
    "full_name": {
        "name": "Full Name",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Full Name", "required": True},
    },
    "who_answers_phone": {
        "name": "Who Answers Phone",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Who Answers Phone"},
    },
    "who_answers_alt_phone": {
        "name": "Who Answers Alt Phone",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Who Answers Alt Phone"},
    },
    "wallet_name": {"name": "Wallet Name", "definition": DEFS["CharField"], "attrs": {"label": "Wallet Name"}},
    "blockchain_name": {
        "name": "Blockchain Name",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Blockchain Name"},
    },
    "wallet_address": {
        "name": "Wallet Address",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Wallet Address"},
    },
    "middle_name": {"name": "Middle Name", "definition": DEFS["CharField"], "attrs": {"label": "Middle Name"}},
    "given_name": {"name": "Given Name", "definition": DEFS["CharField"], "attrs": {"label": "Given Name"}},
    "family_name": {"name": "Family Name", "definition": DEFS["CharField"], "attrs": {"label": "Family Name"}},
    "photo": {"name": "Photo", "definition": {"field_type": fqn(Base64ImageField)}, "attrs": {"label": "Photo"}},
    "disability_certificate_picture": {
        "name": "Disability Certificate Picture",
        "definition": {"field_type": fqn(Base64ImageField)},
        "attrs": {"label": "Disability Certificate Picture"},
    },
}

PEOPLE_FIELDS: dict[str, dict] = {
    "full_name": {
        "name": "Full Name",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Full Name", "required": True},
    },
    "sex": {
        "name": "HOPE IND Sex",
        "definition": {"field_type": fqn(forms.ChoiceField)},
        "attrs": {"label": "Sex"},
    },
    "birth_date": {
        "name": "Birth Date",
        "definition": {"field_type": fqn(forms.DateField)},
        "attrs": {"label": "Birth Date", "required": True},
    },
    "disability": {
        "name": "Disability",
        "definition": DEFS["DisabilityChoices"],
        "attrs": {"label": "Disability"},
    },
    "photo": {"name": "Photo", "definition": {"field_type": fqn(Base64ImageField)}, "attrs": {"label": "Photo"}},
    "observed_disability": {
        "name": "HOPE IND ObservedDisability",
        "definition": {"field_type": fqn(forms.ChoiceField)},
        "attrs": {"label": "Observed Disability"},
    },
    "marital_status": {
        "name": "HOPE IND MaritalStatus",
        "definition": {"field_type": fqn(forms.ChoiceField)},
        "attrs": {"label": "Marital Status"},
    },
    "phone_no": {"name": "Phone No", "definition": DEFS["CharField"], "attrs": {"label": "Phone No"}},
    "phone_no_alternative": {
        "name": "Phone No Alternative",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Phone No Alternative"},
    },
}

INDIVIDUAL_FIELDS: dict[str, dict] = {
    "address": {"name": "Address", "definition": DEFS["CharField"], "attrs": {"label": "Address"}},
    "birth_date": {
        "name": "Birth Date",
        "definition": {"field_type": fqn(forms.DateField)},
        "attrs": {"label": "Birth Date", "required": True},
    },
    "disability": {
        "name": "Disability",
        "definition": DEFS["DisabilityChoices"],
        "attrs": {"label": "Disability"},
    },
    "estimated_birth_date": {
        "name": "Estimated Birth Date",
        "definition": DEFS["BooleanField"],
        "attrs": {"label": "Estimated Birth Date"},
    },
    "family_name": {"name": "Family Name", "definition": DEFS["CharField"], "attrs": {"label": "Family Name"}},
    "full_name": {
        "name": "Full Name",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Full Name", "required": True},
    },
    "sex": {
        "name": "HOPE IND Sex",
        "definition": {"field_type": fqn(forms.ChoiceField)},
        "attrs": {"label": "Sex"},
    },
    "given_name": {"name": "Given Name", "definition": DEFS["CharField"], "attrs": {"label": "Given Name"}},
    "middle_name": {"name": "Middle Name", "definition": DEFS["CharField"], "attrs": {"label": "Middle Name"}},
    "role": {
        "name": "HOPE IND Role",
        "definition": {"field_type": fqn(forms.ChoiceField)},
        "attrs": {"label": "Role"},
    },
    "photo": {"name": "Photo", "definition": {"field_type": fqn(Base64ImageField)}, "attrs": {"label": "Photo"}},
    "phone_no": {"name": "Phone No", "definition": DEFS["CharField"], "attrs": {"label": "Phone No"}},
    "phone_no_alternative": {
        "name": "Phone No Alternative",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Phone No Alternative"},
    },
}


def _get_or_create_field_definition(field_name: str, cfg: dict) -> FieldDefinition:
    definition = cfg["definition"].copy()
    definition["slug"] = slugify(cfg["name"])
    return FieldDefinition.objects.get_or_create(
        name=cfg["name"], field_type=definition["field_type"], defaults=definition
    )[0]


def _delete_field_definition_if_unused(cfg: dict) -> None:
    name = cfg["name"]
    qs = FieldDefinition.objects.filter(name=name)
    if not qs.exists():
        defaults = cfg.get("defaults", {})
        filters = {"slug": defaults.get("slug", slugify(name))}
        if "field_type" in defaults:
            filters["field_type"] = defaults["field_type"]
        qs = FieldDefinition.objects.filter(**filters)
    for fd in qs:
        if not fd.instances.exists():
            fd.delete()


def _delete_fd_if_unused(fd: FieldDefinition) -> None:
    if not fd.instances.exists():
        fd.delete()


def forward() -> None:
    field_registry.register(Base64ImageField)
    field_registry.register(PhoneNumberField)
    with transaction.atomic():
        base_fs, __ = Fieldset.objects.get_or_create(name=INDIVIDUAL_BASE_FIELDSET_NAME)
        for field_name, cfg in FIELDS.items():
            fd = _get_or_create_field_definition(field_name, cfg)
            base_fs.fields.update_or_create(name=field_name, defaults={"definition": fd, "attrs": cfg.get("attrs", {})})

        people_checker = DataChecker.objects.get(name=PEOPLE_CHECKER_NAME)
        individual_checker = DataChecker.objects.get(name=INDIVIDUAL_CHECKER_NAME)
        DataCheckerFieldset.objects.get_or_create(checker=people_checker, fieldset=base_fs, prefix="")
        DataCheckerFieldset.objects.get_or_create(checker=individual_checker, fieldset=base_fs, prefix="")

        people_fs = Fieldset.objects.get(name=PEOPLE_FIELDSET_NAME)
        individual_fs = Fieldset.objects.get(name=INDIVIDUAL_FIELDSET_NAME)
        for name in PEOPLE_FIELDS:
            people_fs.fields.filter(name=name).delete()
        for name in INDIVIDUAL_FIELDS:
            individual_fs.fields.filter(name=name).delete()


def backward() -> None:
    field_registry.register(Base64ImageField)
    field_registry.register(PhoneNumberField)
    with transaction.atomic():
        people_fs = Fieldset.objects.filter(name=PEOPLE_FIELDSET_NAME).first()
        individual_fs = Fieldset.objects.filter(name=INDIVIDUAL_FIELDSET_NAME).first()

        base_fs = Fieldset.objects.filter(name=INDIVIDUAL_BASE_FIELDSET_NAME).first()
        if base_fs:
            DataCheckerFieldset.objects.filter(fieldset=base_fs).delete()
            flex_qs = base_fs.fields.filter(name__in=list(FIELDS.keys())).select_related("definition")
            defs = {ff.definition for ff in flex_qs if ff.definition_id}
            base_fs.fields.filter(name__in=list(FIELDS.keys())).delete()
            for fd in defs:
                _delete_fd_if_unused(fd)
            base_fs.delete()

        if people_fs:
            for name, cfg in PEOPLE_FIELDS.items():
                fd = _get_or_create_field_definition(name, cfg)
                people_fs.fields.update_or_create(name=name, defaults={"definition": fd, "attrs": cfg.get("attrs", {})})

        if individual_fs:
            for name, cfg in INDIVIDUAL_FIELDS.items():
                fd = _get_or_create_field_definition(name, cfg)
                individual_fs.fields.update_or_create(
                    name=name, defaults={"definition": fd, "attrs": cfg.get("attrs", {})}
                )


class Scripts:
    requires = []
    operations = [(forward, backward)]
