# Generated by HCW 0.1.0 on 2025 10 23
from typing import Final

from django.db import transaction
from django.forms.fields import CharField
from hope_flex_fields.models import FieldDefinition
from packaging.version import Version

from country_workspace.contrib.hope.phone_numbers import PhoneNumberField

_script_for_version = Version("0.1.0")

FIELD_NAMES: Final[list] = ["PhoneNo", "PhoneNoAlternative"]
CURRENT_FIELD_TYPE = CharField
UPDATED_FIELD_TYPE = PhoneNumberField


def _apply(field_type: type) -> None:
    fds = FieldDefinition.objects.filter(name__in=FIELD_NAMES)
    for field_definition in fds:
        field_definition.field_type = field_type
        field_definition.save()


@transaction.atomic()
def forward() -> None:
    _apply(UPDATED_FIELD_TYPE)


@transaction.atomic()
def backward() -> None:
    _apply(CURRENT_FIELD_TYPE)


class Scripts:
    requires = []
    operations = [(forward, backward)]
