# Generated by HCW 0.1.0 on 2025 10 27 12:03:30
from packaging.version import Version
from django.db import transaction
from hope_flex_fields.models import FlexField

_script_for_version = Version("0.1.0")


FIELD_LABELS = {
    "address": "Address",
    "admin1": "Geo Location Lvl 1",
    "admin2": "Geo Location Lvl 2",
    "admin3": "Geo Location Lvl 3",
    "admin4": "Geo Location Lvl 4",
    "alternate_collector": "Alternate Collector",
    "birth_date": "Birth Date",
    "consent": "Consent to Share Data",
    "consent_sharing": "Allowed Sharing Partners",
    "country": "Country",
    "country_origin": "Country of Origin",
    "data": "Data",
    "disability": "Disability",
    "document_number": "Document Number",
    "estimated_birth_date": "Estimated Birth Date",
    "expiry_date": "Expiry Date",
    "family_name": "Family Name",
    "female_age_group_0_5_count": "Females 0-5",
    "female_age_group_0_5_disabled_count": "Disabled Females 0-5",
    "female_age_group_12_17_count": "Females 12-17",
    "female_age_group_12_17_disabled_count": "Disabled Females 12-17",
    "female_age_group_18_59_count": "Females 18-59",
    "female_age_group_18_59_disabled_count": "Disabled Females 18-59",
    "female_age_group_60_count": "Females 60+",
    "female_age_group_60_disabled_count": "Disabled Females 60+",
    "female_age_group_6_11_count": "Females 6-11",
    "female_age_group_6_11_disabled_count": "Disabled Females 6-11",
    "financial_institution": "Financial Institution",
    "full_name": "Full Name",
    "given_name": "Given Name",
    "head_of_household": "Head of Household",
    "household_id": "Household ID",
    "image": "Image",
    "index_id": "Index ID",
    "individual_id": "Individual ID",
    "issuance_date": "Issuance Date",
    "male_age_group_0_5_count": "Males 0-5",
    "male_age_group_0_5_disabled_count": "Disabled Males 0-5",
    "male_age_group_12_17_count": "Males 12-17",
    "male_age_group_12_17_disabled_count": "Disabled Males 12-17",
    "male_age_group_18_59_count": "Males 18-59",
    "male_age_group_18_59_disabled_count": "Disabled Males 18-59",
    "male_age_group_60_count": "Males 60+",
    "male_age_group_60_disabled_count": "Disabled Males 60+",
    "male_age_group_6_11_count": "Males 6-11",
    "male_age_group_6_11_disabled_count": "Disabled Males 6-11",
    "marital_status": "Marital Status",
    "middle_name": "Middle Name",
    "name_enumerator": "Enumerator Name",
    "number": "Number",
    "observed_disability": "Observed Disability",
    "org_enumerator": "Enumerator Organization",
    "phone_no": "Phone Number",
    "phone_no_alternative": "Alternate Phone Number",
    "photo": "Photo",
    "pregnant_count": "Pregnant Count",
    "primary_collector": "Primary Collector",
    "registration_method": "Registration Method",
    "relationship": "Relationship",
    "residence_status": "Residence Status",
    "role": "Role",
    "sex": "Sex",
    "size": "Size",
    "type": "Type",
    "village": "Village",
}


@transaction.atomic
def forward() -> None:
    to_update = []
    for flex in FlexField.objects.filter(name__in=FIELD_LABELS):
        attrs = dict(flex.attrs or {})
        if "label" in attrs:
            continue
        attrs["label"] = FIELD_LABELS[flex.name]
        flex.attrs = attrs
        to_update.append(flex)
    if to_update:
        FlexField.objects.bulk_update(to_update, ["attrs"])


@transaction.atomic
def backward() -> None:
    to_update = []
    for flex in FlexField.objects.filter(name__in=FIELD_LABELS):
        attrs = dict(flex.attrs or {})
        if attrs.get("label") != FIELD_LABELS[flex.name]:
            continue
        attrs.pop("label", None)
        flex.attrs = attrs
        to_update.append(flex)
    if to_update:
        FlexField.objects.bulk_update(to_update, ["attrs"])


class Scripts:
    requires = []
    operations = [(forward, backward)]
