# Generated by HCW 0.1.0 on 2025 09 16 18:51:09
from django import forms
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.models import Fieldset, FieldDefinition
from hope_flex_fields.registry import field_registry
from packaging.version import Version
from concurrency.utils import fqn

from country_workspace.contrib.hope.constants import HOUSEHOLD_FIELDSET_NAME
from country_workspace.utils.flex_fields import Base64ImageField
from country_workspace.versioning.choices.currency import CURRENCY_CHOICES

_script_for_version = Version("0.1.0")

DEFS = {
    "CharField": {"field_type": fqn(forms.CharField)},
    "PositiveIntegerField": {"field_type": fqn(forms.IntegerField), "attrs": {"min_value": 0}},
    "BooleanField": {"field_type": fqn(forms.BooleanField), "attrs": {"required": False}},
}

FIELDS = {
    "consent_sign": {
        "name": "Consent Sign",
        "definition": {"field_type": fqn(Base64ImageField)},
        "attrs": {"label": "Consent Sign"},
    },
    "zip_code": {
        "name": "Zip Code",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Zip Code"},
    },
    "children_count": {
        "name": "Children count",
        "definition": DEFS["PositiveIntegerField"],
        "attrs": {"label": "Children count"},
    },
    "male_children_count": {
        "name": "Male Children Count",
        "definition": DEFS["PositiveIntegerField"],
        "attrs": {"label": "Male Children Count"},
    },
    "female_children_count": {
        "name": "Female Children Count",
        "definition": DEFS["PositiveIntegerField"],
        "attrs": {"label": "Female Children Count"},
    },
    "children_disabled_count": {
        "name": "Children Disabled Count",
        "definition": DEFS["PositiveIntegerField"],
        "attrs": {"label": "Children Disabled Count"},
    },
    "male_children_disabled_count": {
        "name": "Male Children Disabled Count",
        "definition": DEFS["PositiveIntegerField"],
        "attrs": {"label": "Male Children Disabled Count"},
    },
    "female_children_disabled_count": {
        "name": "Female Children disabled Count",
        "definition": DEFS["PositiveIntegerField"],
        "attrs": {"label": "Female Children disabled Count"},
    },
    "other_sex_group_count": {
        "name": "Other Sex Group Count",
        "definition": DEFS["PositiveIntegerField"],
        "attrs": {"label": "Other Sex Group Count"},
    },
    "unknown_sex_group_count": {
        "name": "Unknown Sex Group Count",
        "definition": DEFS["PositiveIntegerField"],
        "attrs": {"label": "Unknown Sex Group Count"},
    },
    "returnee": {
        "name": "Returnee",
        "definition": DEFS["BooleanField"],
        "attrs": {"label": "Returnee"},
    },
    "fchild_hoh": {
        "name": "Fchild HOH",
        "definition": DEFS["BooleanField"],
        "attrs": {"label": "Fchild HOH"},
    },
    "child_hoh": {
        "name": "Child HOH",
        "definition": DEFS["BooleanField"],
        "attrs": {"label": "Child HOH"},
    },
    "village": {
        "name": "Village",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Village"},
    },
    "currency": {
        "name": "Currency",
        "definition": {"field_type": fqn(forms.ChoiceField), "attrs": {"choices": CURRENCY_CHOICES}},
        "attrs": {"label": "Currency"},
    },
    "unhcr_id": {
        "name": "Unhcr ID",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Unhcr ID"},
    },
    "detail_id": {
        "name": "Detail ID",
        "definition": DEFS["CharField"],
        "attrs": {"label": "Detail ID"},
    },
    "start": {
        "name": "Start",
        "definition": {"field_type": fqn(forms.DateTimeField)},
        "attrs": {"label": "Start"},
    },
}


def forward() -> None:
    field_registry.register(Base64ImageField)
    with transaction.atomic():
        fs, __ = Fieldset.objects.get_or_create(name=HOUSEHOLD_FIELDSET_NAME)
        for field_name, conf in FIELDS.items():
            conf["definition"]["slug"] = slugify(conf["name"])
            fd, __ = FieldDefinition.objects.get_or_create(
                name=conf["name"], field_type=conf["definition"]["field_type"], defaults=conf["definition"]
            )
            fs.fields.update_or_create(
                name=field_name,
                defaults={
                    "definition": fd,
                    "attrs": conf.get("attrs", {}),
                },
            )


def backward() -> None:
    with transaction.atomic():
        fs = Fieldset.objects.filter(name=HOUSEHOLD_FIELDSET_NAME).first()
        if not fs:
            return

        for field_name, field_def in FIELDS.items():
            fs.fields.filter(name=field_name).delete()
            FieldDefinition.objects.filter(name=field_def["name"]).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
