# Generated by HCW 0.1.0 on 2025 09 17 11:34:18
from typing import Final

from django.db import transaction
from django.forms.fields import CharField
from hope_flex_fields.models import FieldDefinition
from packaging.version import Version

from country_workspace.contrib.hope.phone_numbers import PhoneNumberField

_script_for_version = Version("0.1.0")

PHONE_FIELD_DEFS_TO_REMOVE: Final[list] = ["PhoneNo", "PhoneNoAlternative", "PhoneNumberField"]
PHONE_FIELD_DEFS_TO_FIX: Final[list] = ["Phone No", "Phone No Alternative"]


def _change_field_type(field_type: type) -> None:
    for fdef_to_fix in FieldDefinition.objects.filter(name__in=PHONE_FIELD_DEFS_TO_FIX):
        fdef_to_fix.field_type = field_type
        fdef_to_fix.save()


def _delete_field_defs() -> None:
    FieldDefinition.objects.filter(name__in=PHONE_FIELD_DEFS_TO_REMOVE).delete()


def _create_field_defs() -> None:
    for name in PHONE_FIELD_DEFS_TO_REMOVE:
        FieldDefinition.objects.get_or_create(name=name, defaults={"field_type": PhoneNumberField})


@transaction.atomic()
def forward() -> None:
    _change_field_type(PhoneNumberField)
    _delete_field_defs()


@transaction.atomic()
def backward() -> None:
    _change_field_type(CharField)
    _create_field_defs()


class Scripts:
    requires = []
    operations = [(forward, backward)]
