# Generated by HCW 0.1.0 on 2025 11 04
"""
Upgrade specific ChoiceFields to use ChoiceFieldWithEmptyDisplay.

This solves the UX issue where missing/invalid data in required choice fields
defaults to showing the first option, misleading users.
"""

from typing import Final

from concurrency.utils import fqn
from django import forms
from django.db import transaction
from hope_flex_fields.models import FieldDefinition
from hope_flex_fields.registry import field_registry
from packaging.version import Version

from country_workspace.contrib.hope.required_choice_field import ChoiceFieldWithEmptyDisplay

_script_for_version = Version("0.1.0")

FIELDS_TO_UPGRADE: Final[list[str]] = [
    "HOPE IND Sex",
    "HOPE IND Relationship",
    "Work Status",
    "Disability",
]


def _change_field_type(field_type: type) -> None:
    for field_def in FieldDefinition.objects.filter(name__in=FIELDS_TO_UPGRADE):
        field_def.field_type = field_type
        field_def.save(update_fields=["field_type"])


@transaction.atomic()
def forward() -> None:
    field_registry.register(ChoiceFieldWithEmptyDisplay)
    _change_field_type(fqn(ChoiceFieldWithEmptyDisplay))


@transaction.atomic()
def backward() -> None:
    _change_field_type(fqn(forms.ChoiceField))


class Scripts:
    requires = []
    operations = [(forward, backward)]
