# Generated by HCW 0.1.0 on 2025 11 07 13:06:50
from packaging.version import Version

from django import forms
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.utils import get_kwargs_from_field_class, get_common_attrs

from concurrency.utils import fqn
from hope_flex_fields.models import FieldDefinition, Fieldset, DataChecker
from country_workspace.contrib.hope.constants import ADMINAREAS_FIELDSET_NAME
from country_workspace.contrib.hope.phone_numbers import PhoneNumberField
from country_workspace.contrib.hope.required_choice_field import ChoiceFieldWithEmptyDisplay
from country_workspace.contrib.hope.lookups import FinancialInstitutionChoice
from country_workspace.contrib.hope.geo import CountryChoice
from country_workspace.models import MappingImporter, DataSerializer

_script_for_version = Version("0.1.0")


attrs_default = lambda cls: get_kwargs_from_field_class(cls, get_common_attrs())


NIGERIA_CHECKER_NAME = "HOPE People Nigeria measles rubella campaign"
NIGERIA_CORE_FIELDSET_NAME = "HOPE Nigeria People core"
NIGERIA_ACCOUNT_FIELDSET_NAME = "HOPE Nigeria People account"

FIELDS = {
    "field_consent": {
        "name": forms.BooleanField.__name__,
        "defaults": {
            "field_type": fqn(forms.BooleanField),
            "attrs": attrs_default(forms.BooleanField),
        },
    },
    "field_name_enumerator": {
        "name": "Name Enumerator",
        "defaults": {
            "slug": slugify("Name Enumerator"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_who_to_register": {
        "name": "Who To Register",
        "defaults": {
            "slug": slugify("Who To Register"),
            "field_type": fqn(ChoiceFieldWithEmptyDisplay),
            "attrs": {
                **attrs_default(ChoiceFieldWithEmptyDisplay),
                "choices": [("myself", "Myself"), ("someone_else", "Someone Else")],
            },
        },
    },
    "field_email": {
        "name": forms.EmailField.__name__,
        "defaults": {
            "field_type": fqn(forms.EmailField),
            "attrs": attrs_default(forms.EmailField),
        },
    },
    "field_phone_no": {
        "name": "Phone No",
        "defaults": {
            "slug": slugify("Phone No"),
            "field_type": fqn(PhoneNumberField),
            "attrs": attrs_default(PhoneNumberField),
        },
    },
    "field_birth_date": {
        "name": "Birth Date",
        "defaults": {
            "slug": slugify("Birth Date"),
            "field_type": fqn(forms.DateField),
            "attrs": attrs_default(forms.DateField),
        },
    },
    "field_given_name": {
        "name": "Given Name",
        "defaults": {
            "slug": slugify("Given Name"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_national_id_no": {
        "name": "National ID",
        "defaults": {
            "slug": slugify("National ID No"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_family_name": {
        "name": "Family Name",
        "defaults": {
            "slug": slugify("Family Name"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_middle_name": {
        "name": "Middle Name",
        "defaults": {
            "slug": slugify("Middle Name"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_full_name": {
        "name": "Full Name",
        "defaults": {
            "slug": slugify("Full Name"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_estimated_birth_date": {
        "name": "Estimated Birth Date",
        "defaults": {
            "slug": slugify("Estimated Birth Date"),
            "field_type": fqn(forms.BooleanField),
            "attrs": attrs_default(forms.BooleanField),
        },
    },
    "field_frontline_worker_designation": {
        "name": "Frontline Worker Designation",
        "defaults": {
            "slug": slugify("Frontline Worker Designation"),
            "field_type": fqn(ChoiceFieldWithEmptyDisplay),
            "attrs": {
                **attrs_default(ChoiceFieldWithEmptyDisplay),
                "choices": [("WFP", "Ward Focal Person")],
            },
        },
    },
    "field_account_financial_institution": {
        "name": "Account Financial Institution",
        "defaults": {
            "slug": slugify("Account Financial Institution"),
            "field_type": fqn(FinancialInstitutionChoice),
            "attrs": attrs_default(FinancialInstitutionChoice),
        },
    },
    "field_account_number": {
        "name": "Account Number",
        "defaults": {
            "slug": slugify("Account Number"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_account_uba_code": {
        "name": "UBA Code",
        "defaults": {
            "slug": slugify("UBA Code"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_account_holder_name": {
        "name": "Holder Name",
        "defaults": {
            "slug": slugify("Holder Name"),
            "field_type": fqn(forms.CharField),
            "attrs": attrs_default(forms.CharField),
        },
    },
    "field_country": {
        "name": "Country",
        "defaults": {
            "slug": slugify("Country"),
            "field_type": fqn(CountryChoice),
            "attrs": attrs_default(CountryChoice),
        },
    },
}

SPECS = {
    ADMINAREAS_FIELDSET_NAME: {},  # just to link existing fieldset
    NIGERIA_CORE_FIELDSET_NAME: {
        "description": "Core Information for Nigeria People",
        "flexfields": [
            {
                "name": "consent",
                "definition": FIELDS["field_consent"],
                "attrs": {"label": "Consent to Share Data", "required": False},
            },
            {
                "name": "name_enumerator",  # enumerator_code via mapping importer
                "definition": FIELDS["field_name_enumerator"],
                "attrs": {"label": "Name Enumerator"},
            },
            {
                "name": "who_to_register",
                "definition": FIELDS["field_who_to_register"],
                "attrs": {"label": "Who to Register"},
            },
            {
                "name": "email",
                "definition": FIELDS["field_email"],
                "attrs": {"label": "Email Address"},
            },
            {
                "name": "sex",  # gender via mapping importer
                "definition": "HOPE IND Sex",
                "attrs": {"label": "Sex"},
            },
            {
                "name": "phone_no",
                "definition": FIELDS["field_phone_no"],
                "attrs": {"label": "Phone Number"},
            },
            {
                "name": "birth_date",
                "definition": FIELDS["field_birth_date"],
                "attrs": {"label": "Birth Date"},
            },
            {
                "name": "given_name",
                "definition": FIELDS["field_given_name"],
                "attrs": {"label": "Given Name"},
            },
            {
                "name": "national_id_no",
                "definition": FIELDS["field_national_id_no"],
                "attrs": {"label": "National ID No"},
            },
            {
                "name": "family_name",
                "definition": FIELDS["field_family_name"],
                "attrs": {"label": "Family Name"},
            },
            {
                "name": "middle_name",
                "definition": FIELDS["field_middle_name"],
                "attrs": {"label": "Middle Name"},
            },
            {
                "name": "estimated_birth_date",
                "definition": FIELDS["field_estimated_birth_date"],
                "attrs": {"label": "Estimated Birth Date", "required": False},
            },
            {
                "name": "frontline_worker_designation",
                "definition": FIELDS["field_frontline_worker_designation"],
                "attrs": {"label": "Frontline Worker Designation"},
            },
            {
                "name": "country",
                "definition": FIELDS["field_country"],
                "attrs": {"label": "Country"},
            },
            {
                "name": "full_name",
                "definition": FIELDS["field_full_name"],
                "attrs": {"label": "Full Name"},
            },
            {
                "name": "type",
                "definition": "HOPE People Type",
                "attrs": {"label": "Type"},
            },
        ],
    },
    NIGERIA_ACCOUNT_FIELDSET_NAME: {
        "group": "accounts",
        "prefix": "bank_",
        "description": "Financial Account Information",
        "flexfields": [
            {
                "name": "financial_institution",
                "definition": FIELDS["field_account_financial_institution"],
                "attrs": {"label": "Name"},
            },
            {
                "name": "number",
                "definition": FIELDS["field_account_number"],
                "attrs": {"label": "Number"},
            },
            {
                "name": "uba_code",
                "definition": FIELDS["field_account_uba_code"],
                "attrs": {"label": "UBA Code"},
            },
            {
                "name": "holder_name",
                "definition": FIELDS["field_account_holder_name"],
                "attrs": {"label": "Holder Name"},
            },
        ],
    },
}

NIGERIA_MAPPING_IMPORTER = {
    "name": "nigeria_measles_rubella_campaign_mapping",
    "rules": (
        "gender=sex\n"
        "enumerator_code=name_enumerator\n"
        "account_details_name=bank_financial_institution\n"
        "account_details_number=bank_number\n"
        "account_details_uba_code=bank_uba_code\n"
        "account_details_holder_name=bank_holder_name\n"
    ),
}

NIGERIA_SERIALIZER = {
    "name": "nigeria_measles_rubella_campaign_serializer",
    "code": """//remove null values and move 'uba_code' and 'holder_name' into 'data' object for 'accounts'
function serialize(d){
  function A(x){ return Object.prototype.toString.call(x) === '[object Array]'; }

  function U(s){
    if (typeof s !== 'string') return s;
    s = s.trim();
    var q = s.charAt(0);
    var e = s.charAt(s.length - 1);
    if ((q === "'" || q === '"') && e === q) return s.slice(1, -1);
    return s;
  }

    function acc(a){
    if (!a || typeof a !== 'object') return U(a);

    var r = {};
    var data = {};
    var k, v;

    for (k in a){
      if (!Object.prototype.hasOwnProperty.call(a, k)) continue;
      v = a[k];
      if (v == null) continue;

      if (k === 'uba_code' || k === 'holder_name'){
        data[k] = clean(v);
      } else {
        r[k] = clean(v);
      }
    }

    // add data only if it's not empty
    for (k in data){
      if (Object.prototype.hasOwnProperty.call(data, k)){
        r.data = data;
        break;
      }
    }
    return r;
  }

  function clean(v){
    var i, k, val, o, j;

    if (A(v)){
      var arr = [];
      for (i = 0; i < v.length; i++) arr.push(clean(v[i]));
      return arr;
    }

    if (v && typeof v === 'object'){
      o = {};

      if (A(v.accounts)){
        var accs = [];
        for (j = 0; j < v.accounts.length; j++) accs.push(acc(v.accounts[j]));
        o.accounts = accs;
      }

      for (k in v){
        if (!Object.prototype.hasOwnProperty.call(v, k)) continue;
        if (k === 'accounts') continue;
        val = v[k];
        if (val == null) continue;
        o[k] = clean(val);
      }
      return o;
    }

    return U(v);
  }

  return clean(d);
}
""",
}


@transaction.atomic
def forward() -> None:
    dc, __ = DataChecker.objects.get_or_create(name=NIGERIA_CHECKER_NAME)
    for fieldset_name, spec in SPECS.items():
        fs, __ = Fieldset.objects.get_or_create(
            name=fieldset_name,
            defaults={"group": spec.get("group", ""), "description": spec.get("description", "")},
        )
        for field in spec.get("flexfields", []):
            fd = (
                FieldDefinition.objects.get(name=defn)
                if isinstance(defn := field["definition"], str)
                else FieldDefinition.objects.update_or_create(**defn)[0]
            )
            fs.fields.update_or_create(
                name=field["name"],
                defaults={"definition": fd, "attrs": field.get("attrs") or {}},
            )
        dc.fieldsets.through.objects.update_or_create(
            checker=dc,
            fieldset=fs,
            defaults={"prefix": spec.get("prefix", "")},
        )
    MappingImporter.objects.update_or_create(data_checker=dc, defaults=NIGERIA_MAPPING_IMPORTER)

    obj, created = DataSerializer.objects.get_or_create(**NIGERIA_SERIALIZER)
    if not created and obj.code != NIGERIA_SERIALIZER["code"]:
        obj.code = NIGERIA_SERIALIZER["code"]
        obj.full_clean()
        obj.save(update_fields=["code"])


@transaction.atomic
def backward() -> None:
    if not (dc := DataChecker.objects.filter(name=NIGERIA_CHECKER_NAME).first()):
        return

    for fs_name, spec in SPECS.items():
        if not (fs := Fieldset.objects.filter(name=fs_name).first()):
            continue
        ffs = spec.get("flexfields", [])

        if ff_names := [f["name"] for f in ffs]:
            fs.fields.filter(name__in=ff_names).delete()
        dc.fieldsets.remove(fs)
        if fs_name != ADMINAREAS_FIELDSET_NAME and not fs.fields.exists():
            fs.delete()
        if fd_names := {d["name"] for x in ffs if isinstance((d := x.get("definition")), dict) and d.get("name")}:
            FieldDefinition.objects.filter(name__in=fd_names, instances__isnull=True).delete()

    MappingImporter.objects.filter(data_checker=dc).delete()
    if not dc.fieldsets.exists():
        dc.delete()

    DataSerializer.objects.filter(name=NIGERIA_SERIALIZER["name"], code=NIGERIA_SERIALIZER["code"]).delete()


class Scripts:
    requires = []
    operations = [(forward, backward)]
