# Generated by HCW 0.1.0 on 2025 12 19

from django import forms
from django.db import transaction
from packaging.version import Version
from concurrency.utils import fqn
from hope_flex_fields.models import FieldDefinition
from hope_flex_fields.registry import field_registry

from country_workspace.utils.flex_fields import ObservedDisabilityChoice

_script_for_version = Version("0.1.0")

FIELD_NAME = "HOPE IND ObservedDisability"


def _change_field_type(field_type: str) -> None:
    FieldDefinition.objects.filter(name=FIELD_NAME).update(field_type=field_type)


@transaction.atomic()
def forward() -> None:
    field_registry.register(ObservedDisabilityChoice)
    _change_field_type(fqn(ObservedDisabilityChoice))


@transaction.atomic()
def backward() -> None:
    _change_field_type(fqn(forms.ChoiceField))


class Scripts:
    requires = []
    operations = [(forward, backward)]
