# Generated by HCW 0.1.0 on 2026 02 18
from packaging.version import Version
from django.db import transaction
from django.utils.text import slugify
from hope_flex_fields.models import FieldDefinition, FlexField

_script_for_version = Version("0.1.0")

FLEX_FIELDS_FWD = {
    "alternate_collector": "alternate_collector_id",
    "primary_collector": "primary_collector_id",
    "head_of_household": "head_of_household_id",
}

FIELD_DEFINITIONS_FWD = {
    "Alternate Collector Reference ID": "alternate_collector_id",
    "Primary Collector Reference ID": "primary_collector_id",
    "Head of Household ID": "head_of_household_id",
}

ROLE_LABELS = {
    "alternate_collector_id": "Alternate Collector ID",
    "primary_collector_id": "Primary Collector ID",
    "head_of_household_id": "Head of Household ID",
}


def _rename_flex_fields(name_map: dict[str, str]) -> None:
    fields = FlexField.objects.filter(name__in=name_map).select_related("fieldset")
    for field in fields:
        new_name = name_map[field.name]
        if field.name == new_name:
            continue
        if FlexField.objects.filter(fieldset=field.fieldset, name=new_name).exclude(pk=field.pk).exists():
            continue
        field.name = new_name
        field.slug = slugify(new_name)
        field.save(update_fields=["name", "slug"])


def _rename_field_definitions(name_map: dict[str, str]) -> None:
    for old_name, new_name in name_map.items():
        fd = FieldDefinition.objects.filter(name=old_name).first()
        if not fd:
            continue
        if FieldDefinition.objects.filter(name=new_name).exclude(pk=fd.pk).exists():
            continue
        fd.name = new_name
        fd.slug = slugify(new_name)
        fd.save(update_fields=["name", "slug"])


def _apply_role_labels() -> None:
    to_update = []
    for field in FlexField.objects.filter(name__in=ROLE_LABELS):
        attrs = dict(field.attrs or {})
        if attrs.get("label") == ROLE_LABELS[field.name]:
            continue
        attrs["label"] = ROLE_LABELS[field.name]
        field.attrs = attrs
        to_update.append(field)
    if to_update:
        FlexField.objects.bulk_update(to_update, ["attrs"])


@transaction.atomic
def forward() -> None:
    _rename_flex_fields(FLEX_FIELDS_FWD)
    _rename_field_definitions(FIELD_DEFINITIONS_FWD)
    _apply_role_labels()


@transaction.atomic
def backward() -> None:
    _rename_flex_fields({v: k for k, v in FLEX_FIELDS_FWD.items()})
    _rename_field_definitions({v: k for k, v in FIELD_DEFINITIONS_FWD.items()})


class Scripts:
    requires = []
    operations = [(forward, backward)]
