# Generated by HCW 0.1.0 on 2026 02 20 15:56:20
from hope_flex_fields.models import FlexField
from packaging.version import Version

_script_for_version = Version("0.1.0")

full_name_old_attrs = {"label": "Full Name", "required": True}
full_name_new_attrs = {"label": "Full Name", "required": True, "min_length": 2}


def forward() -> None:
    full_name_ff = FlexField.objects.filter(name="full_name").first()
    if full_name_ff:
        full_name_ff.attrs = full_name_new_attrs
        full_name_ff.save()


def backward() -> None:
    full_name_ff = FlexField.objects.filter(name="full_name").first()
    if full_name_ff:
        full_name_ff.attrs = full_name_old_attrs
        full_name_ff.save()


class Scripts:
    requires = []
    operations = [(forward, backward)]
