# Generated by HCW 0.1.0 on 2026 09 09
from concurrency.utils import fqn
from django.db import transaction
from django.db.models import Q
from django.utils.text import slugify
from hope_flex_fields.models import FieldDefinition, FlexField
from hope_flex_fields.registry import field_registry
from packaging.version import Version

from country_workspace.utils.flex_fields import Base64ImageField, FlexImageField

_script_for_version = Version("0.1.0")


def _repoint(source: type, target: type) -> None:
    FieldDefinition.objects.filter(field_type=fqn(source)).update(field_type=fqn(target))


def _rename_or_merge(source: type, target: type) -> None:
    """Make the definition named after the replaced field class follow the rename.

    `0001_initial` creates a definition for every registered field, so on a fresh
    install the new name is already taken. Merging into it leaves fresh and
    upgraded databases with the same single definition for the new class.
    """
    old = FieldDefinition.objects.filter(name=source.__name__).first()
    if not old:
        return
    new_name = target.__name__
    new = FieldDefinition.objects.filter(Q(name=new_name) | Q(slug=slugify(new_name))).exclude(pk=old.pk).first()
    if new is None:
        old.name = new_name
        old.slug = slugify(new_name)
        old.save(update_fields=["name", "slug"])
        return
    FlexField.objects.filter(definition=old).update(definition=new)
    if not old.instances.exists():
        old.delete()


@transaction.atomic()
def forward() -> None:
    _repoint(Base64ImageField, FlexImageField)
    _rename_or_merge(Base64ImageField, FlexImageField)


@transaction.atomic()
def backward() -> None:
    # a definition merged away by forward() comes back with default attributes only
    field_registry.register(Base64ImageField)
    _repoint(FlexImageField, Base64ImageField)
    _rename_or_merge(FlexImageField, Base64ImageField)


class Scripts:
    requires = []
    operations = [(forward, backward)]
