# Generated by HCW 0.1.0 on 2026 09 24
"""Add optional *_latin flex fields to store the Latin spelling of beneficiary names.

Mirrors HOPE's `Individual.given_name_latin` / `middle_name_latin` / `family_name_latin` /
`full_name_latin` columns (see `hope.models.individual.LATIN_NAME_FIELDS`). No transliteration
or other processing is applied: the fields are optional and are stored exactly as provided by
the source.

Adding them to the shared "HOPE Individual core base" fieldset makes them available on both the
Individual and the People checkers, since script 0028 links that fieldset to both (see
`DataCheckerFieldset.objects.get_or_create(checker=..., fieldset=base_fs, prefix="")`).
"""

from concurrency.utils import fqn
from django.db import transaction
from hope_flex_fields.models import Fieldset, FieldDefinition
from hope_flex_fields.registry import field_registry
from packaging.version import Version

from country_workspace.contrib.hope.constants import INDIVIDUAL_BASE_FIELDSET_NAME
from country_workspace.contrib.hope.latin_names import LatinNameField

_script_for_version = Version("0.1.0")

LATIN_NAME_DEFINITION = {"field_type": fqn(LatinNameField)}

# field name -> (FieldDefinition name, FlexField attrs)
FIELDS: dict[str, dict] = {
    "given_name_latin": {
        "name": "Given Name Latin",
        "attrs": {"label": "Given Name Latin", "required": False, "max_length": 150},
    },
    "middle_name_latin": {
        "name": "Middle Name Latin",
        "attrs": {"label": "Middle Name Latin", "required": False, "max_length": 150},
    },
    "family_name_latin": {
        "name": "Family Name Latin",
        "attrs": {"label": "Family Name Latin", "required": False, "max_length": 150},
    },
    "full_name_latin": {
        "name": "Full Name Latin",
        "attrs": {"label": "Full Name Latin", "required": False, "max_length": 500, "min_length": 2},
    },
}


def _get_or_create_field_definition(cfg: dict) -> FieldDefinition:
    return FieldDefinition.objects.get_or_create(
        name=cfg["name"],
        field_type=LATIN_NAME_DEFINITION["field_type"],
    )[0]


def _delete_fd_if_unused(fd: FieldDefinition) -> None:
    if not fd.instances.exists():
        fd.delete()


def forward() -> None:
    field_registry.register(LatinNameField)
    with transaction.atomic():
        base_fs, __ = Fieldset.objects.get_or_create(name=INDIVIDUAL_BASE_FIELDSET_NAME)
        for field_name, cfg in FIELDS.items():
            fd = _get_or_create_field_definition(cfg)
            base_fs.fields.update_or_create(name=field_name, defaults={"definition": fd, "attrs": cfg["attrs"]})


def backward() -> None:
    field_registry.register(LatinNameField)
    with transaction.atomic():
        base_fs = Fieldset.objects.filter(name=INDIVIDUAL_BASE_FIELDSET_NAME).first()
        if not base_fs:
            return

        flex_qs = base_fs.fields.filter(name__in=list(FIELDS.keys())).select_related("definition")
        defs = {ff.definition for ff in flex_qs if ff.definition_id}
        base_fs.fields.filter(name__in=list(FIELDS.keys())).delete()
        for fd in defs:
            _delete_fd_if_unused(fd)


class Scripts:
    requires = []
    operations = [(forward, backward)]
