# Generated by Django 5.1.3 on 2025-02-18 08:18

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("country_workspace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this project as defined in the Aurora system.", max_length=500
                    ),
                ),
                (
                    "reference_pk",
                    models.IntegerField(help_text="The unique identifier for this project within the Aurora system."),
                ),
                (
                    "program",
                    models.OneToOneField(
                        blank=True,
                        help_text="Links this project to a specific Program within the CW system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="country_workspace.program",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("version", concurrency.fields.IntegerVersionField(default=0, help_text="record revision number")),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this registration as defined in the Aurora system.", max_length=200
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this registration is currently active in the Aurora system.",
                    ),
                ),
                (
                    "reference_pk",
                    models.IntegerField(
                        help_text="The unique identifier for this registration within the Aurora system."
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associates this registration with a project, as defined in the Aurora system.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="aurora.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
