# Generated by Django 5.2.11 on 2026-02-09 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aurora", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"permissions": (("sync_aurora_project", "Can sync Aurora project"),)},
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={"permissions": (("sync_aurora_registration", "Can sync Aurora registration"),)},
        ),
    ]
