# Generated by Django 5.2.3 on 2025-07-03 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country_workspace", "0018_rdp_hope_rdi_id_alter_rdp_status"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryRdp",
            fields=[],
            options={
                "verbose_name": "Country Registration Data Push",
                "verbose_name_plural": "Country Registration Data Pushes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("country_workspace.rdp",),
        ),
    ]
