# Generated by Django 5.2.9 on 2025-12-18 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "country_workspace",
            "0036_alter_individual_options_alter_office_options_and_more",
        ),
        ("workspaces", "0002_countryrdp"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryMappingImporter",
            fields=[],
            options={
                "verbose_name": "Mapping",
                "verbose_name_plural": "Mappings",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("country_workspace.mappingimporter",),
        ),
    ]
