# Generated by Django 5.1.1 on 2024-10-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hope_country_workspace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryHousehold",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hope_country_workspace.household",),
        ),
    ]
