# Generated by Django 5.2.8 on 2025-11-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KoboSubmission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_uid", models.CharField(editable=False, max_length=32, unique=True)),
                ("last_submission_id", models.IntegerField(editable=False)),
            ],
        ),
    ]
