# Generated by Django 5.2.8 on 2025-11-11 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kobo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KoboSubmission",
        ),
    ]
