name: CI
on:
  pull_request:
    branches: [develop] # If more branches are needed, add them here.
    types: [synchronize, opened, reopened, ready_for_review]
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker buildx create --use

          docker buildx build \
            --tag unicef/hope_country_workspace:${{ github.sha }} \
            --load \
            --target python_dev_deps \
            -f ./docker/Dockerfile \
            ./
      - name: Run the tests
        run: |
          docker compose -f ./.github/docker/compose.ci.yml up --exit-code-from tests