# This file will be used when creating PRs to the develop branch.
# It should run the tests without building the docker images.

name: CI
on:
  pull_request:
    branches: [develop] # If more branches are needed, add them here.
    types: [synchronize, opened, reopened, ready_for_review]
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install pdm
        pdm install
    - name: Run tests
      run: |
        docker compose run --rm -d db
        pdm run pytest