name: "Documentation"

on:
  push:
    branches:
      - develop
      - master
  schedule:
    - cron: '37 23 * * 2'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Doc
        run: |
            pip install "mkdocs>=1.6.1" "markdown-include" "mkdocs-material>=9.5.36" \
                          "mkdocs-awesome-pages-plugin>=2.9.3" "mkdocstrings-python" "mdx-gh-links>=0.4"
            mkdocs build -d ./docs-output

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs-output

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
